"""Generates src/wdb/stmts.rs from Wazuh's wazuh_db/wdb.h (enum wdb_stmt) and
wazuh_db/wdb.c (SQL_STMT), so the statement table is the C one verbatim.

Usage: python gen_stmts.py <wazuh src> <out .rs>
"""
import re
import sys

src, out = sys.argv[1], sys.argv[2]
h = open(src + '/wazuh_db/wdb.h', encoding='utf-8').read()
c = open(src + '/wazuh_db/wdb.c', encoding='utf-8').read()
macros = {}
for m in re.finditer(r'#define\s+(WM_TASK_STATUS_\w+)\s+"([^"]*)"',
                     open(src + '/wazuh_modules/wm_task_general.h', encoding='utf-8').read()):
    macros[m.group(1)] = m.group(2)

body = h[h.index('typedef enum wdb_stmt {'):]
body = body[:body.index('} wdb_stmt;')]
names = re.findall(r'^\s*(WDB_STMT_\w+)', body, re.M)
assert names[-1] == 'WDB_STMT_SIZE'
names = names[:-1]

table = c[c.index('static const char *SQL_STMT[] = {'):]
table = table[:table.index('\n};')]
sql = {}
for m in re.finditer(r'\[(WDB_STMT_\w+)\]\s*=\s*((?:"(?:[^"\\]|\\.)*"|\s|WM_TASK_STATUS_\w+)+),', table):
    parts = re.findall(r'"((?:[^"\\]|\\.)*)"|(WM_TASK_STATUS_\w+)', m.group(2))
    s = ''.join(p[0] if p[0] or not p[1] else macros[p[1]] for p in parts)
    assert '\\' not in s, s
    sql[m.group(1)] = s
missing = [n for n in names if n not in sql]
assert not missing, missing

with open(out, 'w', encoding='utf-8', newline='\n') as f:
    f.write('//! `enum wdb_stmt` and `SQL_STMT` (wazuh_db/wdb.h, wazuh_db/wdb.c).\n')
    f.write('//! Generated by tools/gen_stmts.py from the C sources: do not edit.\n\n')
    for i, n in enumerate(names):
        f.write(f'pub const {n}: usize = {i};\n')
    f.write(f'/// `WDB_STMT_SIZE`\npub const WDB_STMT_SIZE: usize = {len(names)};\n\n')
    f.write('/// `SQL_STMT`\npub static SQL_STMT: [&str; WDB_STMT_SIZE] = [\n')
    for n in names:
        s = sql[n].replace('\\', '\\\\').replace('"', '\\"')
        f.write(f'    "{s}",\n')
    f.write('];\n')
print(len(names), 'statements')
