"""Generates src/wdb/tables.rs from the dbsync column tables of Wazuh's
wazuh_db/wdb_parser.c (TABLE_* and TABLE_MAP).

Usage: python gen_tables.py <wazuh src> <out .rs>
"""
import re
import sys

src, out = sys.argv[1], sys.argv[2]
c = open(src + '/wazuh_db/wdb_parser.c', encoding='utf-8').read()

tables = {}
for m in re.finditer(r'static struct column_list const (TABLE_\w+)\[[^\]]*\] = \{\n(.*?)\n\};', c, re.S):
    name, body = m.group(1), m.group(2)
    rows = []
    for r in re.finditer(r'\{\s*\.value\s*=\s*\{\s*(FIELD_\w+),\s*(\d+),\s*(true|false),\s*(true|false),\s*(NULL|"[^"]*"),\s*"([^"]*)",\s*\{\.(\w+)\s*=\s*([^}]*)\},\s*(true|false)\s*\}', body):
        ftype, idx, aux, pk, source, target, dkind, dval, conv = r.groups()
        rows.append((ftype, int(idx), aux == 'true', pk == 'true', None if source == 'NULL' else source.strip('"'), target, dkind, dval.strip(), conv == 'true'))
    assert rows, name
    for i, r in enumerate(rows):
        assert r[1] == i + 1, (name, r)
    tables[name] = rows

m = re.search(r'static struct kv_list const TABLE_MAP\[\] = \{\n(.*?)\n\};', c, re.S)
mapping = re.findall(r'\{\s*"(\w+)",\s*"(\w+)",\s*(true|false),\s*(TABLE_\w+),\s*(\w+)\s*\}', m.group(1))
assert len(mapping) == 13, mapping


def default(kind, val):
    if kind == 'integer':
        return 'Default::Int(%s)' % val
    if kind == 'integer_long':
        return 'Default::Long(%s)' % val.rstrip('L')
    if kind == 'real':
        return 'Default::Real(%s)' % val
    if kind == 'text':
        return 'Default::Text(%s)' % val
    raise SystemExit(kind)


with open(out, 'w', encoding='utf-8', newline='\n') as f:
    f.write('''//! The dbsync column tables of wazuh_db/wdb_parser.c (`TABLE_*`,
//! `TABLE_MAP`). Generated by tools/gen_tables.py: do not edit.

/// `field_type_t`
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FieldType {
    Integer,
    Text,
    Real,
    IntegerLong,
}

/// `default_value`
#[derive(Debug, Clone, Copy)]
pub enum Default {
    Int(i32),
    Long(i64),
    Real(f64),
    Text(&'static str),
}

/// `struct field`
#[derive(Debug, Clone, Copy)]
pub struct Field {
    pub type_: FieldType,
    pub index: i32,
    pub is_aux_field: bool,
    pub is_pk: bool,
    pub source_name: Option<&'static str>,
    pub target_name: &'static str,
    pub default_value: Default,
    pub convert_empty_string_as_null: bool,
}

/// `struct kv`
#[derive(Debug, Clone, Copy)]
pub struct Kv {
    pub key: &'static str,
    pub value: &'static str,
    pub single_row_table: bool,
    pub column_list: &'static [Field],
    pub field_count: usize,
}

''')
    tmap = {'FIELD_INTEGER': 'Integer', 'FIELD_TEXT': 'Text', 'FIELD_REAL': 'Real', 'FIELD_INTEGER_LONG': 'IntegerLong'}
    for name, rows in tables.items():
        f.write('pub static %s: [Field; %d] = [\n' % (name, len(rows)))
        for (ftype, idx, aux, pk, source, target, dkind, dval, conv) in rows:
            src_s = 'None' if source is None else 'Some("%s")' % source
            f.write('    Field { type_: FieldType::%s, index: %d, is_aux_field: %s, is_pk: %s, source_name: %s, target_name: "%s", default_value: %s, convert_empty_string_as_null: %s },\n'
                    % (tmap[ftype], idx, str(aux).lower(), str(pk).lower(), src_s, target, default(dkind, dval), str(conv).lower()))
        f.write('];\n\n')
    counts = {}
    for mm in re.finditer(r'#define (\w+_FIELD_COUNT) (\d+)', c):
        counts[mm.group(1)] = int(mm.group(2))
    f.write('/// `TABLE_MAP`\npub static TABLE_MAP: [Kv; %d] = [\n' % len(mapping))
    for key, value, single, table, count in mapping:
        f.write('    Kv { key: "%s", value: "%s", single_row_table: %s, column_list: &%s, field_count: %d },\n'
                % (key, value, single, table, counts[count]))
    f.write('];\n')
print(len(tables), 'tables')
