//! wazuh-db's usage counters (wazuh_db/wdb_state.c).
//! Generated by tools/gen_state.py from the C source: do not edit.

#![allow(non_snake_case)]

use std::collections::HashMap;

use parking_lot::{Mutex, MutexGuard};
use siem_cjson::Json;

const ARGV0: &str = "wazuh-db";

/// `struct timeval`
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct Tv {
    pub sec: i64,
    pub usec: i64,
}

impl Tv {
    /// `timersub(end, begin)`
    pub fn diff(end: Tv, begin: Tv) -> Tv {
        let mut sec = end.sec - begin.sec;
        let mut usec = end.usec - begin.usec;
        if usec < 0 {
            sec -= 1;
            usec += 1_000_000;
        }
        Tv { sec, usec }
    }

    /// `timeradd`
    pub fn add(self, o: Tv) -> Tv {
        let mut sec = self.sec + o.sec;
        let mut usec = self.usec + o.usec;
        if usec >= 1_000_000 {
            sec += 1;
            usec -= 1_000_000;
        }
        Tv { sec, usec }
    }

    /// `timeval_to_milis`
    pub fn ms(self) -> u64 {
        (self.sec as u64).wrapping_mul(1000).wrapping_add((self.usec / 1000) as u64)
    }
}

/// `wdb_state_t`
#[derive(Debug, Clone, Default)]
pub struct Counters {
    pub uptime: i64,
    n: HashMap<&'static str, u64>,
    t: HashMap<&'static str, Tv>,
}

impl Counters {
    fn inc(&mut self, k: &'static str) {
        *self.n.entry(k).or_default() += 1;
    }

    fn add(&mut self, k: &'static str, time: Tv) {
        let e = self.t.entry(k).or_default();
        *e = e.add(time);
    }

    /// A query counter.
    pub fn n(&self, k: &str) -> u64 {
        self.n.get(k).copied().unwrap_or(0)
    }

    fn tv(&self, k: &str) -> Tv {
        self.t.get(k).copied().unwrap_or_default()
    }

    /// A time counter in milliseconds.
    pub fn ms(&self, k: &str) -> u64 {
        self.tv(k).ms()
    }

    fn sum(&self, terms: &[&str]) -> u64 {
        let mut t = Tv::default();
        for k in terms {
            t = t.add(self.tv(k));
        }
        t.ms()
    }

    /// `get_agent_time`
    pub fn get_agent_time(&self) -> u64 {
        self.sum(&[
            "queries_breakdown.agent_breakdown.sql_time",
            "queries_breakdown.agent_breakdown.remove_time",
            "queries_breakdown.agent_breakdown.open_calls_time",
            "queries_breakdown.agent_breakdown.vacuum_time",
            "queries_breakdown.agent_breakdown.get_fragmentation_time",
            "queries_breakdown.agent_breakdown.sleep_time",
            "queries_breakdown.agent_breakdown.begin_time",
            "queries_breakdown.agent_breakdown.commit_time",
            "queries_breakdown.agent_breakdown.close_time",
            "queries_breakdown.agent_breakdown.syscheck.syscheck_time",
            "queries_breakdown.agent_breakdown.syscheck.fim_file_time",
            "queries_breakdown.agent_breakdown.syscheck.fim_registry_time",
            "queries_breakdown.agent_breakdown.syscheck.fim_registry_key_time",
            "queries_breakdown.agent_breakdown.syscheck.fim_registry_value_time",
            "queries_breakdown.agent_breakdown.rootcheck.rootcheck_time",
            "queries_breakdown.agent_breakdown.sca.sca_time",
            "queries_breakdown.agent_breakdown.ciscat.ciscat_time",
            "queries_breakdown.agent_breakdown.syscollector.syscollector_processes_time",
            "queries_breakdown.agent_breakdown.syscollector.syscollector_packages_time",
            "queries_breakdown.agent_breakdown.syscollector.syscollector_hotfixes_time",
            "queries_breakdown.agent_breakdown.syscollector.syscollector_ports_time",
            "queries_breakdown.agent_breakdown.syscollector.syscollector_network_protocol_time",
            "queries_breakdown.agent_breakdown.syscollector.syscollector_network_address_time",
            "queries_breakdown.agent_breakdown.syscollector.syscollector_network_iface_time",
            "queries_breakdown.agent_breakdown.syscollector.syscollector_hwinfo_time",
            "queries_breakdown.agent_breakdown.syscollector.syscollector_osinfo_time",
            "queries_breakdown.agent_breakdown.syscollector.deprecated.process_time",
            "queries_breakdown.agent_breakdown.syscollector.deprecated.package_time",
            "queries_breakdown.agent_breakdown.syscollector.deprecated.hotfix_time",
            "queries_breakdown.agent_breakdown.syscollector.deprecated.port_time",
            "queries_breakdown.agent_breakdown.syscollector.deprecated.netproto_time",
            "queries_breakdown.agent_breakdown.syscollector.deprecated.netaddr_time",
            "queries_breakdown.agent_breakdown.syscollector.deprecated.netinfo_time",
            "queries_breakdown.agent_breakdown.syscollector.deprecated.hardware_time",
            "queries_breakdown.agent_breakdown.syscollector.deprecated.osinfo_time",
            "queries_breakdown.agent_breakdown.sync.dbsync_time",
        ])
    }

    /// `get_global_time`
    pub fn get_global_time(&self) -> u64 {
        self.sum(&[
            "queries_breakdown.global_breakdown.sql_time",
            "queries_breakdown.global_breakdown.backup_time",
            "queries_breakdown.global_breakdown.open_calls_time",
            "queries_breakdown.global_breakdown.vacuum_time",
            "queries_breakdown.global_breakdown.get_fragmentation_time",
            "queries_breakdown.global_breakdown.sleep_time",
            "queries_breakdown.global_breakdown.agent.insert_agent_time",
            "queries_breakdown.global_breakdown.agent.update_agent_data_time",
            "queries_breakdown.global_breakdown.agent.update_agent_name_time",
            "queries_breakdown.global_breakdown.agent.update_keepalive_time",
            "queries_breakdown.global_breakdown.agent.update_connection_status_time",
            "queries_breakdown.global_breakdown.agent.update_status_code_time",
            "queries_breakdown.global_breakdown.agent.reset_agents_connection_time",
            "queries_breakdown.global_breakdown.agent.delete_agent_time",
            "queries_breakdown.global_breakdown.agent.select_agent_name_time",
            "queries_breakdown.global_breakdown.agent.select_agent_group_time",
            "queries_breakdown.global_breakdown.agent.find_agent_time",
            "queries_breakdown.global_breakdown.agent.get_agent_info_time",
            "queries_breakdown.global_breakdown.agent.get_all_agents_time",
            "queries_breakdown.global_breakdown.agent.get_distinct_groups_time",
            "queries_breakdown.global_breakdown.agent.get_agents_by_connection_status_time",
            "queries_breakdown.global_breakdown.agent.disconnect_agents_time",
            "queries_breakdown.global_breakdown.agent.sync_agent_info_get_time",
            "queries_breakdown.global_breakdown.agent.sync_agent_info_set_time",
            "queries_breakdown.global_breakdown.agent.sync_agent_groups_get_time",
            "queries_breakdown.global_breakdown.agent.set_agent_groups_time",
            "queries_breakdown.global_breakdown.agent.get_groups_integrity_time",
            "queries_breakdown.global_breakdown.agent.recalculate_agent_group_hashes_time",
            "queries_breakdown.global_breakdown.group.insert_agent_group_time",
            "queries_breakdown.global_breakdown.group.delete_group_time",
            "queries_breakdown.global_breakdown.group.select_groups_time",
            "queries_breakdown.global_breakdown.group.find_group_time",
            "queries_breakdown.global_breakdown.belongs.select_group_belong_time",
            "queries_breakdown.global_breakdown.belongs.get_group_agent_time",
            "queries_breakdown.global_breakdown.labels.get_labels_time",
        ])
    }

    /// `get_task_time`
    pub fn get_task_time(&self) -> u64 {
        self.sum(&[
            "queries_breakdown.task_breakdown.sql_time",
            "queries_breakdown.task_breakdown.tasks.upgrade_time",
            "queries_breakdown.task_breakdown.tasks.upgrade_custom_time",
            "queries_breakdown.task_breakdown.tasks.upgrade_get_status_time",
            "queries_breakdown.task_breakdown.tasks.upgrade_update_status_time",
            "queries_breakdown.task_breakdown.tasks.upgrade_result_time",
            "queries_breakdown.task_breakdown.tasks.upgrade_cancel_tasks_time",
            "queries_breakdown.task_breakdown.tasks.set_timeout_time",
            "queries_breakdown.task_breakdown.tasks.delete_old_time",
        ])
    }

    /// `get_time_total`
    pub fn get_time_total(&self) -> u64 {
        self.get_task_time() + self.get_global_time() + self.get_agent_time() + self.ms("queries_breakdown.wazuhdb_breakdown.remove_time") + self.ms("queries_breakdown.mitre_breakdown.sql_time")
    }
}

/// `wdb_state` with its mutex.
#[derive(Debug, Default)]
pub struct State {
    m: Mutex<Counters>,
}

/// Builds a cJSON object tree in insertion order (objects are added to
/// their parents before being filled, like the C code does).
struct Builder {
    nodes: Vec<Vec<(&'static str, Item)>>,
}

enum Item {
    Num(f64),
    Str(&'static str),
    Node(usize),
}

impl Builder {
    fn obj(&mut self) -> usize {
        self.nodes.push(Vec::new());
        self.nodes.len() - 1
    }
    fn node(&mut self, parent: usize, k: &'static str, child: usize) {
        self.nodes[parent].push((k, Item::Node(child)));
    }
    fn num(&mut self, parent: usize, k: &'static str, v: f64) {
        self.nodes[parent].push((k, Item::Num(v)));
    }
    fn string(&mut self, parent: usize, k: &'static str, v: &'static str) {
        self.nodes[parent].push((k, Item::Str(v)));
    }
    fn build(&self, i: usize) -> Json {
        let mut o = Json::object();
        for (k, v) in &self.nodes[i] {
            let j = match v {
                Item::Num(n) => Json::number(*n),
                Item::Str(s) => Json::string(s),
                Item::Node(c) => self.build(*c),
            };
            o.add(k, j);
        }
        o
    }
}

impl State {
    fn lock(&self) -> MutexGuard<'_, Counters> {
        self.m.lock()
    }

    /// A copy of the counters.
    pub fn snapshot(&self) -> Counters {
        self.lock().clone()
    }

    /// `wdb_state.uptime = ...`
    pub fn set_uptime(&self, t: i64) {
        self.lock().uptime = t;
    }

    pub fn w_inc_queries_total(&self) {
        let mut g = self.lock();
        g.inc("queries_total");
    }

    pub fn w_inc_wazuhdb(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.wazuhdb_queries");
    }

    pub fn w_inc_wazuhdb_remove(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.wazuhdb_breakdown.remove_queries");
    }

    pub fn w_inc_wazuhdb_remove_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.wazuhdb_breakdown.remove_time", time);
    }

    pub fn w_inc_agent(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_queries");
    }

    pub fn w_inc_agent_open_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.open_calls_time", time);
    }

    pub fn w_inc_agent_sql(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.sql_queries");
    }

    pub fn w_inc_agent_sql_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.sql_time", time);
    }

    pub fn w_inc_agent_remove(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.remove_queries");
    }

    pub fn w_inc_agent_remove_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.remove_time", time);
    }

    pub fn w_inc_agent_begin(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.begin_queries");
    }

    pub fn w_inc_agent_begin_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.begin_time", time);
    }

    pub fn w_inc_agent_commit(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.commit_queries");
    }

    pub fn w_inc_agent_commit_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.commit_time", time);
    }

    pub fn w_inc_agent_close(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.close_queries");
    }

    pub fn w_inc_agent_close_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.close_time", time);
    }

    pub fn w_inc_agent_vacuum(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.vacuum_queries");
    }

    pub fn w_inc_agent_vacuum_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.vacuum_time", time);
    }

    pub fn w_inc_agent_get_fragmentation(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.get_fragmentation_queries");
    }

    pub fn w_inc_agent_get_fragmentation_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.get_fragmentation_time", time);
    }

    pub fn w_inc_agent_rootcheck(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.rootcheck.rootcheck_queries");
    }

    pub fn w_inc_agent_rootcheck_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.rootcheck.rootcheck_time", time);
    }

    pub fn w_inc_agent_sca(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.sca.sca_queries");
    }

    pub fn w_inc_agent_sca_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.sca.sca_time", time);
    }

    pub fn w_inc_agent_ciscat(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.ciscat.ciscat_queries");
    }

    pub fn w_inc_agent_ciscat_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.ciscat.ciscat_time", time);
    }

    pub fn w_inc_agent_dbsync(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.sync.dbsync_queries");
    }

    pub fn w_inc_agent_dbsync_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.sync.dbsync_time", time);
    }

    pub fn w_inc_agent_syscheck(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscheck.syscheck_queries");
    }

    pub fn w_inc_agent_syscheck_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.syscheck.syscheck_time", time);
    }

    pub fn w_inc_agent_fim_file(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscheck.fim_file_queries");
    }

    pub fn w_inc_agent_fim_file_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.syscheck.fim_file_time", time);
    }

    pub fn w_inc_agent_fim_registry(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscheck.fim_registry_queries");
    }

    pub fn w_inc_agent_fim_registry_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.syscheck.fim_registry_time", time);
    }

    pub fn w_inc_agent_fim_registry_key(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscheck.fim_registry_key_queries");
    }

    pub fn w_inc_agent_fim_registry_key_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.syscheck.fim_registry_key_time", time);
    }

    pub fn w_inc_agent_fim_registry_value(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscheck.fim_registry_value_queries");
    }

    pub fn w_inc_agent_fim_registry_value_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.syscheck.fim_registry_value_time", time);
    }

    pub fn w_inc_agent_syscollector_processes(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.syscollector_processes_queries");
    }

    pub fn w_inc_agent_syscollector_packages(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.syscollector_packages_queries");
    }

    pub fn w_inc_agent_syscollector_hotfixes(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.syscollector_hotfixes_queries");
    }

    pub fn w_inc_agent_syscollector_ports(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.syscollector_ports_queries");
    }

    pub fn w_inc_agent_syscollector_network_protocol(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.syscollector_network_protocol_queries");
    }

    pub fn w_inc_agent_syscollector_network_address(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.syscollector_network_address_queries");
    }

    pub fn w_inc_agent_syscollector_network_iface(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.syscollector_network_iface_queries");
    }

    pub fn w_inc_agent_syscollector_hwinfo(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.syscollector_hwinfo_queries");
    }

    pub fn w_inc_agent_syscollector_osinfo(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.syscollector_osinfo_queries");
    }

    pub fn w_inc_agent_syscollector_users(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.syscollector_users_queries");
    }

    pub fn w_inc_agent_syscollector_groups(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.syscollector_groups_queries");
    }

    pub fn w_inc_agent_syscollector_browser_extensions(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.syscollector_browser_extensions_queries");
    }

    pub fn w_inc_agent_syscollector_services(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.syscollector_services_queries");
    }

    pub fn w_inc_agent_syscollector_times(&self, time: Tv, type_: i32) {
        let mut g = self.lock();
        match type_ {
            c if c == super::WDB_SYSCOLLECTOR_PROCESSES => {
                g.add("queries_breakdown.agent_breakdown.syscollector.syscollector_processes_time", time);
            }
            c if c == super::WDB_SYSCOLLECTOR_PACKAGES => {
                g.add("queries_breakdown.agent_breakdown.syscollector.syscollector_packages_time", time);
            }
            c if c == super::WDB_SYSCOLLECTOR_HOTFIXES => {
                g.add("queries_breakdown.agent_breakdown.syscollector.syscollector_hotfixes_time", time);
            }
            c if c == super::WDB_SYSCOLLECTOR_PORTS => {
                g.add("queries_breakdown.agent_breakdown.syscollector.syscollector_ports_time", time);
            }
            c if c == super::WDB_SYSCOLLECTOR_NETPROTO => {
                g.add("queries_breakdown.agent_breakdown.syscollector.syscollector_network_protocol_time", time);
            }
            c if c == super::WDB_SYSCOLLECTOR_NETADDRESS => {
                g.add("queries_breakdown.agent_breakdown.syscollector.syscollector_network_address_time", time);
            }
            c if c == super::WDB_SYSCOLLECTOR_NETINFO => {
                g.add("queries_breakdown.agent_breakdown.syscollector.syscollector_network_iface_time", time);
            }
            c if c == super::WDB_SYSCOLLECTOR_HWINFO => {
                g.add("queries_breakdown.agent_breakdown.syscollector.syscollector_hwinfo_time", time);
            }
            c if c == super::WDB_SYSCOLLECTOR_OSINFO => {
                g.add("queries_breakdown.agent_breakdown.syscollector.syscollector_osinfo_time", time);
            }
            c if c == super::WDB_SYSCOLLECTOR_GROUPS => {
                g.add("queries_breakdown.agent_breakdown.syscollector.syscollector_groups_time", time);
            }
            c if c == super::WDB_SYSCOLLECTOR_SERVICES => {
                g.add("queries_breakdown.agent_breakdown.syscollector.syscollector_services_time", time);
            }
            c if c == super::WDB_SYSCOLLECTOR_USERS => {
                g.add("queries_breakdown.agent_breakdown.syscollector.syscollector_users_time", time);
            }
            c if c == super::WDB_SYSCOLLECTOR_BROWSER_EXTENSIONS => {
                g.add("queries_breakdown.agent_breakdown.syscollector.syscollector_browser_extensions_time", time);
            }
            _ => {
            }
        }
    }

    pub fn w_inc_agent_syscollector_deprecated_process(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.deprecated.process_queries");
    }

    pub fn w_inc_agent_syscollector_deprecated_process_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.syscollector.deprecated.process_time", time);
    }

    pub fn w_inc_agent_syscollector_deprecated_packages(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.deprecated.package_queries");
    }

    pub fn w_inc_agent_syscollector_deprecated_packages_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.syscollector.deprecated.package_time", time);
    }

    pub fn w_inc_agent_syscollector_deprecated_hotfixes(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.deprecated.hotfix_queries");
    }

    pub fn w_inc_agent_syscollector_deprecated_hotfixes_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.syscollector.deprecated.hotfix_time", time);
    }

    pub fn w_inc_agent_syscollector_deprecated_ports(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.deprecated.port_queries");
    }

    pub fn w_inc_agent_syscollector_deprecated_ports_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.syscollector.deprecated.port_time", time);
    }

    pub fn w_inc_agent_syscollector_deprecated_network_protocol(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.deprecated.netproto_queries");
    }

    pub fn w_inc_agent_syscollector_deprecated_network_protocol_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.syscollector.deprecated.netproto_time", time);
    }

    pub fn w_inc_agent_syscollector_deprecated_network_address(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.deprecated.netaddr_queries");
    }

    pub fn w_inc_agent_syscollector_deprecated_network_address_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.syscollector.deprecated.netaddr_time", time);
    }

    pub fn w_inc_agent_syscollector_deprecated_network_info(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.deprecated.netinfo_queries");
    }

    pub fn w_inc_agent_syscollector_deprecated_network_info_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.syscollector.deprecated.netinfo_time", time);
    }

    pub fn w_inc_agent_syscollector_deprecated_hardware(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.deprecated.hardware_queries");
    }

    pub fn w_inc_agent_syscollector_deprecated_hardware_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.syscollector.deprecated.hardware_time", time);
    }

    pub fn w_inc_agent_syscollector_deprecated_osinfo(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.syscollector.deprecated.osinfo_queries");
    }

    pub fn w_inc_agent_syscollector_deprecated_osinfo_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.syscollector.deprecated.osinfo_time", time);
    }

    pub fn w_inc_agent_sleep(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.agent_breakdown.sleep_queries");
    }

    pub fn w_inc_agent_sleep_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.agent_breakdown.sleep_time", time);
    }

    pub fn w_inc_global(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_queries");
    }

    pub fn w_inc_global_open_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.open_calls_time", time);
    }

    pub fn w_inc_global_sql(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.sql_queries");
    }

    pub fn w_inc_global_sql_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.sql_time", time);
    }

    pub fn w_inc_global_backup(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.backup_queries");
    }

    pub fn w_inc_global_backup_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.backup_time", time);
    }

    pub fn w_inc_global_agent_insert_agent(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.insert_agent_queries");
    }

    pub fn w_inc_global_agent_insert_agent_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.insert_agent_time", time);
    }

    pub fn w_inc_global_agent_update_agent_data(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.update_agent_data_queries");
    }

    pub fn w_inc_global_agent_update_agent_data_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.update_agent_data_time", time);
    }

    pub fn w_inc_global_agent_update_agent_name(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.update_agent_name_queries");
    }

    pub fn w_inc_global_agent_update_agent_name_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.update_agent_name_time", time);
    }

    pub fn w_inc_global_agent_update_keepalive(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.update_keepalive_queries");
    }

    pub fn w_inc_global_agent_update_keepalive_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.update_keepalive_time", time);
    }

    pub fn w_inc_global_agent_update_connection_status(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.update_connection_status_queries");
    }

    pub fn w_inc_global_agent_update_connection_status_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.update_connection_status_time", time);
    }

    pub fn w_inc_global_agent_update_status_code(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.update_status_code_queries");
    }

    pub fn w_inc_global_agent_update_status_code_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.update_status_code_time", time);
    }

    pub fn w_inc_global_agent_reset_agents_connection(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.reset_agents_connection_queries");
    }

    pub fn w_inc_global_agent_reset_agents_connection_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.reset_agents_connection_time", time);
    }

    pub fn w_inc_global_agent_delete_agent(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.delete_agent_queries");
    }

    pub fn w_inc_global_agent_delete_agent_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.delete_agent_time", time);
    }

    pub fn w_inc_global_agent_select_agent_name(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.select_agent_name_queries");
    }

    pub fn w_inc_global_agent_select_agent_name_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.select_agent_name_time", time);
    }

    pub fn w_inc_global_agent_select_agent_group(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.select_agent_group_queries");
    }

    pub fn w_inc_global_agent_select_agent_group_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.select_agent_group_time", time);
    }

    pub fn w_inc_global_agent_find_agent(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.find_agent_queries");
    }

    pub fn w_inc_global_agent_find_agent_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.find_agent_time", time);
    }

    pub fn w_inc_global_agent_get_agent_info(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.get_agent_info_queries");
    }

    pub fn w_inc_global_agent_get_agent_info_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.get_agent_info_time", time);
    }

    pub fn w_inc_global_agent_get_all_agents(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.get_all_agents_queries");
    }

    pub fn w_inc_global_agent_get_all_agents_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.get_all_agents_time", time);
    }

    pub fn w_inc_global_agent_get_distinct_groups(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.get_distinct_groups_queries");
    }

    pub fn w_inc_global_agent_get_distinct_groups_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.get_distinct_groups_time", time);
    }

    pub fn w_inc_global_agent_get_agents_by_connection_status(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.get_agents_by_connection_status_queries");
    }

    pub fn w_inc_global_agent_get_agents_by_connection_status_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.get_agents_by_connection_status_time", time);
    }

    pub fn w_inc_global_agent_disconnect_agents(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.disconnect_agents_queries");
    }

    pub fn w_inc_global_agent_disconnect_agents_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.disconnect_agents_time", time);
    }

    pub fn w_inc_global_agent_sync_agent_info_get(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.sync_agent_info_get_queries");
    }

    pub fn w_inc_global_agent_sync_agent_info_get_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.sync_agent_info_get_time", time);
    }

    pub fn w_inc_global_agent_sync_agent_info_set(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.sync_agent_info_set_queries");
    }

    pub fn w_inc_global_agent_sync_agent_info_set_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.sync_agent_info_set_time", time);
    }

    pub fn w_inc_global_agent_sync_agent_groups_get(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.sync_agent_groups_get_queries");
    }

    pub fn w_inc_global_agent_sync_agent_groups_get_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.sync_agent_groups_get_time", time);
    }

    pub fn w_inc_global_agent_set_agent_groups(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.set_agent_groups_queries");
    }

    pub fn w_inc_global_agent_set_agent_groups_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.set_agent_groups_time", time);
    }

    pub fn w_inc_global_agent_get_groups_integrity(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.get_groups_integrity_queries");
    }

    pub fn w_inc_global_agent_get_groups_integrity_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.get_groups_integrity_time", time);
    }

    pub fn w_inc_global_agent_recalculate_agent_group_hashes(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.agent.recalculate_agent_group_hashes_queries");
    }

    pub fn w_inc_global_agent_recalculate_agent_group_hashes_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.agent.recalculate_agent_group_hashes_time", time);
    }

    pub fn w_inc_global_group_insert_agent_group(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.group.insert_agent_group_queries");
    }

    pub fn w_inc_global_group_insert_agent_group_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.group.insert_agent_group_time", time);
    }

    pub fn w_inc_global_group_delete_group(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.group.delete_group_queries");
    }

    pub fn w_inc_global_group_delete_group_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.group.delete_group_time", time);
    }

    pub fn w_inc_global_group_select_groups(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.group.select_groups_queries");
    }

    pub fn w_inc_global_group_select_groups_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.group.select_groups_time", time);
    }

    pub fn w_inc_global_group_find_group(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.group.find_group_queries");
    }

    pub fn w_inc_global_group_find_group_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.group.find_group_time", time);
    }

    pub fn w_inc_global_belongs_select_group_belong(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.belongs.select_group_belong_queries");
    }

    pub fn w_inc_global_belongs_select_group_belong_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.belongs.select_group_belong_time", time);
    }

    pub fn w_inc_global_belongs_get_group_agent(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.belongs.get_group_agent_queries");
    }

    pub fn w_inc_global_belongs_get_group_agent_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.belongs.get_group_agent_time", time);
    }

    pub fn w_inc_global_labels_get_labels(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.labels.get_labels_queries");
    }

    pub fn w_inc_global_labels_get_labels_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.labels.get_labels_time", time);
    }

    pub fn w_inc_global_vacuum(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.vacuum_queries");
    }

    pub fn w_inc_global_vacuum_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.vacuum_time", time);
    }

    pub fn w_inc_global_get_fragmentation(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.get_fragmentation_queries");
    }

    pub fn w_inc_global_get_fragmentation_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.get_fragmentation_time", time);
    }

    pub fn w_inc_global_sleep(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.global_breakdown.sleep_queries");
    }

    pub fn w_inc_global_sleep_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.global_breakdown.sleep_time", time);
    }

    pub fn w_inc_task(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.task_queries");
    }

    pub fn w_inc_task_sql(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.task_breakdown.sql_queries");
    }

    pub fn w_inc_task_sql_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.task_breakdown.sql_time", time);
    }

    pub fn w_inc_task_set_timeout(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.task_breakdown.tasks.set_timeout_queries");
    }

    pub fn w_inc_task_set_timeout_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.task_breakdown.tasks.set_timeout_time", time);
    }

    pub fn w_inc_task_delete_old(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.task_breakdown.tasks.delete_old_queries");
    }

    pub fn w_inc_task_delete_old_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.task_breakdown.tasks.delete_old_time", time);
    }

    pub fn w_inc_task_upgrade(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.task_breakdown.tasks.upgrade_queries");
    }

    pub fn w_inc_task_upgrade_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.task_breakdown.tasks.upgrade_time", time);
    }

    pub fn w_inc_task_upgrade_custom(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.task_breakdown.tasks.upgrade_custom_queries");
    }

    pub fn w_inc_task_upgrade_custom_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.task_breakdown.tasks.upgrade_custom_time", time);
    }

    pub fn w_inc_task_upgrade_get_status(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.task_breakdown.tasks.upgrade_get_status_queries");
    }

    pub fn w_inc_task_upgrade_get_status_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.task_breakdown.tasks.upgrade_get_status_time", time);
    }

    pub fn w_inc_task_upgrade_update_status(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.task_breakdown.tasks.upgrade_update_status_queries");
    }

    pub fn w_inc_task_upgrade_update_status_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.task_breakdown.tasks.upgrade_update_status_time", time);
    }

    pub fn w_inc_task_upgrade_result(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.task_breakdown.tasks.upgrade_result_queries");
    }

    pub fn w_inc_task_upgrade_result_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.task_breakdown.tasks.upgrade_result_time", time);
    }

    pub fn w_inc_task_upgrade_cancel_tasks(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.task_breakdown.tasks.upgrade_cancel_tasks_queries");
    }

    pub fn w_inc_task_upgrade_cancel_tasks_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.task_breakdown.tasks.upgrade_cancel_tasks_time", time);
    }

    pub fn w_inc_mitre(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.mitre_queries");
    }

    pub fn w_inc_mitre_sql(&self) {
        let mut g = self.lock();
        g.inc("queries_breakdown.mitre_breakdown.sql_queries");
    }

    pub fn w_inc_mitre_sql_time(&self, time: Tv) {
        let mut g = self.lock();
        g.add("queries_breakdown.mitre_breakdown.sql_time", time);
    }

    /// `wdb_create_state_json` (`now`: `time(NULL)`)
    pub fn create_state_json(&self, now: i64) -> Json {
        let s = self.snapshot();
        let mut b = Builder { nodes: Vec::new() };
        let wdb_state_json = b.obj();
        b.num(wdb_state_json, "uptime", s.uptime as f64);
        b.num(wdb_state_json, "timestamp", now as f64);
        b.string(wdb_state_json, "name", ARGV0);
        let _metrics = b.obj();
        b.node(wdb_state_json, "metrics", _metrics);
        let _queries = b.obj();
        b.node(_metrics, "queries", _queries);
        b.num(_queries, "received", s.n("queries_total") as f64);
        let _received_breakdown = b.obj();
        b.node(_queries, "received_breakdown", _received_breakdown);
        b.num(_received_breakdown, "agent", s.n("queries_breakdown.agent_queries") as f64);
        let _agent_breakdown = b.obj();
        b.node(_received_breakdown, "agent_breakdown", _agent_breakdown);
        let _agent_db = b.obj();
        b.node(_agent_breakdown, "db", _agent_db);
        b.num(_agent_db, "begin", s.n("queries_breakdown.agent_breakdown.begin_queries") as f64);
        b.num(_agent_db, "close", s.n("queries_breakdown.agent_breakdown.close_queries") as f64);
        b.num(_agent_db, "commit", s.n("queries_breakdown.agent_breakdown.commit_queries") as f64);
        b.num(_agent_db, "remove", s.n("queries_breakdown.agent_breakdown.remove_queries") as f64);
        b.num(_agent_db, "sql", s.n("queries_breakdown.agent_breakdown.sql_queries") as f64);
        b.num(_agent_db, "vacuum", s.n("queries_breakdown.agent_breakdown.vacuum_queries") as f64);
        b.num(_agent_db, "get_fragmentation", s.n("queries_breakdown.agent_breakdown.get_fragmentation_queries") as f64);
        b.num(_agent_db, "sleep", s.n("queries_breakdown.agent_breakdown.sleep_queries") as f64);
        let _agent_tables = b.obj();
        b.node(_agent_breakdown, "tables", _agent_tables);
        let _agent_tables_ciscat = b.obj();
        b.node(_agent_tables, "ciscat", _agent_tables_ciscat);
        b.num(_agent_tables_ciscat, "ciscat", s.n("queries_breakdown.agent_breakdown.ciscat.ciscat_queries") as f64);
        let _agent_tables_rootcheck = b.obj();
        b.node(_agent_tables, "rootcheck", _agent_tables_rootcheck);
        b.num(_agent_tables_rootcheck, "rootcheck", s.n("queries_breakdown.agent_breakdown.rootcheck.rootcheck_queries") as f64);
        let _agent_tables_sca = b.obj();
        b.node(_agent_tables, "sca", _agent_tables_sca);
        b.num(_agent_tables_sca, "sca", s.n("queries_breakdown.agent_breakdown.sca.sca_queries") as f64);
        let _agent_tables_sync = b.obj();
        b.node(_agent_tables, "sync", _agent_tables_sync);
        b.num(_agent_tables_sync, "dbsync", s.n("queries_breakdown.agent_breakdown.sync.dbsync_queries") as f64);
        let _agent_tables_syscheck = b.obj();
        b.node(_agent_tables, "syscheck", _agent_tables_syscheck);
        b.num(_agent_tables_syscheck, "fim_file", s.n("queries_breakdown.agent_breakdown.syscheck.fim_file_queries") as f64);
        b.num(_agent_tables_syscheck, "fim_registry", s.n("queries_breakdown.agent_breakdown.syscheck.fim_registry_queries") as f64);
        b.num(_agent_tables_syscheck, "fim_registry_key", s.n("queries_breakdown.agent_breakdown.syscheck.fim_registry_key_queries") as f64);
        b.num(_agent_tables_syscheck, "fim_registry_value", s.n("queries_breakdown.agent_breakdown.syscheck.fim_registry_value_queries") as f64);
        b.num(_agent_tables_syscheck, "syscheck", s.n("queries_breakdown.agent_breakdown.syscheck.syscheck_queries") as f64);
        let _agent_tables_syscollector = b.obj();
        b.node(_agent_tables, "syscollector", _agent_tables_syscollector);
        b.num(_agent_tables_syscollector, "syscollector_hotfixes", s.n("queries_breakdown.agent_breakdown.syscollector.syscollector_hotfixes_queries") as f64);
        b.num(_agent_tables_syscollector, "syscollector_hwinfo", s.n("queries_breakdown.agent_breakdown.syscollector.syscollector_hwinfo_queries") as f64);
        b.num(_agent_tables_syscollector, "syscollector_network_address", s.n("queries_breakdown.agent_breakdown.syscollector.syscollector_network_address_queries") as f64);
        b.num(_agent_tables_syscollector, "syscollector_network_iface", s.n("queries_breakdown.agent_breakdown.syscollector.syscollector_network_iface_queries") as f64);
        b.num(_agent_tables_syscollector, "syscollector_network_protocol", s.n("queries_breakdown.agent_breakdown.syscollector.syscollector_network_protocol_queries") as f64);
        b.num(_agent_tables_syscollector, "syscollector_osinfo", s.n("queries_breakdown.agent_breakdown.syscollector.syscollector_osinfo_queries") as f64);
        b.num(_agent_tables_syscollector, "syscollector_packages", s.n("queries_breakdown.agent_breakdown.syscollector.syscollector_packages_queries") as f64);
        b.num(_agent_tables_syscollector, "syscollector_ports", s.n("queries_breakdown.agent_breakdown.syscollector.syscollector_ports_queries") as f64);
        b.num(_agent_tables_syscollector, "syscollector_processes", s.n("queries_breakdown.agent_breakdown.syscollector.syscollector_processes_queries") as f64);
        b.num(_agent_tables_syscollector, "syscollector_users", s.n("queries_breakdown.agent_breakdown.syscollector.syscollector_users_queries") as f64);
        b.num(_agent_tables_syscollector, "syscollector_groups", s.n("queries_breakdown.agent_breakdown.syscollector.syscollector_groups_queries") as f64);
        b.num(_agent_tables_syscollector, "syscollector_browser_extensions", s.n("queries_breakdown.agent_breakdown.syscollector.syscollector_browser_extensions_queries") as f64);
        b.num(_agent_tables_syscollector, "syscollector_services", s.n("queries_breakdown.agent_breakdown.syscollector.syscollector_services_queries") as f64);
        let _agent_tables_syscollector_deprecated = b.obj();
        b.node(_agent_tables_syscollector, "deprecated", _agent_tables_syscollector_deprecated);
        b.num(_agent_tables_syscollector_deprecated, "hardware", s.n("queries_breakdown.agent_breakdown.syscollector.deprecated.hardware_queries") as f64);
        b.num(_agent_tables_syscollector_deprecated, "hotfix", s.n("queries_breakdown.agent_breakdown.syscollector.deprecated.hotfix_queries") as f64);
        b.num(_agent_tables_syscollector_deprecated, "netaddr", s.n("queries_breakdown.agent_breakdown.syscollector.deprecated.netaddr_queries") as f64);
        b.num(_agent_tables_syscollector_deprecated, "netinfo", s.n("queries_breakdown.agent_breakdown.syscollector.deprecated.netinfo_queries") as f64);
        b.num(_agent_tables_syscollector_deprecated, "netproto", s.n("queries_breakdown.agent_breakdown.syscollector.deprecated.netproto_queries") as f64);
        b.num(_agent_tables_syscollector_deprecated, "osinfo", s.n("queries_breakdown.agent_breakdown.syscollector.deprecated.osinfo_queries") as f64);
        b.num(_agent_tables_syscollector_deprecated, "package", s.n("queries_breakdown.agent_breakdown.syscollector.deprecated.package_queries") as f64);
        b.num(_agent_tables_syscollector_deprecated, "port", s.n("queries_breakdown.agent_breakdown.syscollector.deprecated.port_queries") as f64);
        b.num(_agent_tables_syscollector_deprecated, "process", s.n("queries_breakdown.agent_breakdown.syscollector.deprecated.process_queries") as f64);
        b.num(_received_breakdown, "global", s.n("queries_breakdown.global_queries") as f64);
        let _global_breakdown = b.obj();
        b.node(_received_breakdown, "global_breakdown", _global_breakdown);
        let _global_db = b.obj();
        b.node(_global_breakdown, "db", _global_db);
        b.num(_global_db, "backup", s.n("queries_breakdown.global_breakdown.backup_queries") as f64);
        b.num(_global_db, "sql", s.n("queries_breakdown.global_breakdown.sql_queries") as f64);
        b.num(_global_db, "vacuum", s.n("queries_breakdown.global_breakdown.vacuum_queries") as f64);
        b.num(_global_db, "get_fragmentation", s.n("queries_breakdown.global_breakdown.get_fragmentation_queries") as f64);
        b.num(_global_db, "sleep", s.n("queries_breakdown.global_breakdown.sleep_queries") as f64);
        let _global_tables = b.obj();
        b.node(_global_breakdown, "tables", _global_tables);
        let _global_tables_agent = b.obj();
        b.node(_global_tables, "agent", _global_tables_agent);
        b.num(_global_tables_agent, "delete-agent", s.n("queries_breakdown.global_breakdown.agent.delete_agent_queries") as f64);
        b.num(_global_tables_agent, "disconnect-agents", s.n("queries_breakdown.global_breakdown.agent.disconnect_agents_queries") as f64);
        b.num(_global_tables_agent, "find-agent", s.n("queries_breakdown.global_breakdown.agent.find_agent_queries") as f64);
        b.num(_global_tables_agent, "get-agent-info", s.n("queries_breakdown.global_breakdown.agent.get_agent_info_queries") as f64);
        b.num(_global_tables_agent, "get-agents-by-connection-status", s.n("queries_breakdown.global_breakdown.agent.get_agents_by_connection_status_queries") as f64);
        b.num(_global_tables_agent, "get-all-agents", s.n("queries_breakdown.global_breakdown.agent.get_all_agents_queries") as f64);
        b.num(_global_tables_agent, "get-distinct-groups", s.n("queries_breakdown.global_breakdown.agent.get_distinct_groups_queries") as f64);
        b.num(_global_tables_agent, "get-groups-integrity", s.n("queries_breakdown.global_breakdown.agent.get_groups_integrity_queries") as f64);
        b.num(_global_tables_agent, "recalculate-agent-group-hashes", s.n("queries_breakdown.global_breakdown.agent.recalculate_agent_group_hashes_queries") as f64);
        b.num(_global_tables_agent, "insert-agent", s.n("queries_breakdown.global_breakdown.agent.insert_agent_queries") as f64);
        b.num(_global_tables_agent, "reset-agents-connection", s.n("queries_breakdown.global_breakdown.agent.reset_agents_connection_queries") as f64);
        b.num(_global_tables_agent, "select-agent-group", s.n("queries_breakdown.global_breakdown.agent.select_agent_group_queries") as f64);
        b.num(_global_tables_agent, "select-agent-name", s.n("queries_breakdown.global_breakdown.agent.select_agent_name_queries") as f64);
        b.num(_global_tables_agent, "set-agent-groups", s.n("queries_breakdown.global_breakdown.agent.set_agent_groups_queries") as f64);
        b.num(_global_tables_agent, "sync-agent-groups-get", s.n("queries_breakdown.global_breakdown.agent.sync_agent_groups_get_queries") as f64);
        b.num(_global_tables_agent, "sync-agent-info-get", s.n("queries_breakdown.global_breakdown.agent.sync_agent_info_get_queries") as f64);
        b.num(_global_tables_agent, "sync-agent-info-set", s.n("queries_breakdown.global_breakdown.agent.sync_agent_info_set_queries") as f64);
        b.num(_global_tables_agent, "update-agent-data", s.n("queries_breakdown.global_breakdown.agent.update_agent_data_queries") as f64);
        b.num(_global_tables_agent, "update-agent-name", s.n("queries_breakdown.global_breakdown.agent.update_agent_name_queries") as f64);
        b.num(_global_tables_agent, "update-connection-status", s.n("queries_breakdown.global_breakdown.agent.update_connection_status_queries") as f64);
        b.num(_global_tables_agent, "update-status-code", s.n("queries_breakdown.global_breakdown.agent.update_status_code_queries") as f64);
        b.num(_global_tables_agent, "update-keepalive", s.n("queries_breakdown.global_breakdown.agent.update_keepalive_queries") as f64);
        let _global_tables_belongs = b.obj();
        b.node(_global_tables, "belongs", _global_tables_belongs);
        b.num(_global_tables_belongs, "get-group-agents", s.n("queries_breakdown.global_breakdown.belongs.get_group_agent_queries") as f64);
        b.num(_global_tables_belongs, "select-group-belong", s.n("queries_breakdown.global_breakdown.belongs.select_group_belong_queries") as f64);
        let _global_tables_group = b.obj();
        b.node(_global_tables, "group", _global_tables_group);
        b.num(_global_tables_group, "delete-group", s.n("queries_breakdown.global_breakdown.group.delete_group_queries") as f64);
        b.num(_global_tables_group, "find-group", s.n("queries_breakdown.global_breakdown.group.find_group_queries") as f64);
        b.num(_global_tables_group, "insert-agent-group", s.n("queries_breakdown.global_breakdown.group.insert_agent_group_queries") as f64);
        b.num(_global_tables_group, "select-groups", s.n("queries_breakdown.global_breakdown.group.select_groups_queries") as f64);
        let _global_tables_labels = b.obj();
        b.node(_global_tables, "labels", _global_tables_labels);
        b.num(_global_tables_labels, "get-labels", s.n("queries_breakdown.global_breakdown.labels.get_labels_queries") as f64);
        b.num(_received_breakdown, "mitre", s.n("queries_breakdown.mitre_queries") as f64);
        let _mitre_breakdown = b.obj();
        b.node(_received_breakdown, "mitre_breakdown", _mitre_breakdown);
        let _mitre_db = b.obj();
        b.node(_mitre_breakdown, "db", _mitre_db);
        b.num(_mitre_db, "sql", s.n("queries_breakdown.mitre_breakdown.sql_queries") as f64);
        b.num(_received_breakdown, "task", s.n("queries_breakdown.task_queries") as f64);
        let _task_breakdown = b.obj();
        b.node(_received_breakdown, "task_breakdown", _task_breakdown);
        let _task_db = b.obj();
        b.node(_task_breakdown, "db", _task_db);
        b.num(_task_db, "sql", s.n("queries_breakdown.task_breakdown.sql_queries") as f64);
        let _task_tables = b.obj();
        b.node(_task_breakdown, "tables", _task_tables);
        let _task_tables_tasks = b.obj();
        b.node(_task_tables, "tasks", _task_tables_tasks);
        b.num(_task_tables_tasks, "delete_old", s.n("queries_breakdown.task_breakdown.tasks.delete_old_queries") as f64);
        b.num(_task_tables_tasks, "set_timeout", s.n("queries_breakdown.task_breakdown.tasks.set_timeout_queries") as f64);
        b.num(_task_tables_tasks, "upgrade", s.n("queries_breakdown.task_breakdown.tasks.upgrade_queries") as f64);
        b.num(_task_tables_tasks, "upgrade_cancel_tasks", s.n("queries_breakdown.task_breakdown.tasks.upgrade_cancel_tasks_queries") as f64);
        b.num(_task_tables_tasks, "upgrade_custom", s.n("queries_breakdown.task_breakdown.tasks.upgrade_custom_queries") as f64);
        b.num(_task_tables_tasks, "upgrade_get_status", s.n("queries_breakdown.task_breakdown.tasks.upgrade_get_status_queries") as f64);
        b.num(_task_tables_tasks, "upgrade_result", s.n("queries_breakdown.task_breakdown.tasks.upgrade_result_queries") as f64);
        b.num(_task_tables_tasks, "upgrade_update_status", s.n("queries_breakdown.task_breakdown.tasks.upgrade_update_status_queries") as f64);
        b.num(_received_breakdown, "wazuhdb", s.n("queries_breakdown.wazuhdb_queries") as f64);
        let _wazuhdb_breakdown = b.obj();
        b.node(_received_breakdown, "wazuhdb_breakdown", _wazuhdb_breakdown);
        let _wazuhdb_db = b.obj();
        b.node(_wazuhdb_breakdown, "db", _wazuhdb_db);
        b.num(_wazuhdb_db, "remove", s.n("queries_breakdown.wazuhdb_breakdown.remove_queries") as f64);
        let _time = b.obj();
        b.node(_metrics, "time", _time);
        b.num(_time, "execution", s.get_time_total() as f64);
        let _execution_breakdown = b.obj();
        b.node(_time, "execution_breakdown", _execution_breakdown);
        b.num(_execution_breakdown, "agent", s.get_agent_time() as f64);
        let _agent_breakdown_t = b.obj();
        b.node(_execution_breakdown, "agent_breakdown", _agent_breakdown_t);
        let _agent_db_t = b.obj();
        b.node(_agent_breakdown_t, "db", _agent_db_t);
        b.num(_agent_db_t, "open", s.ms("queries_breakdown.agent_breakdown.open_calls_time") as f64);
        b.num(_agent_db_t, "begin", s.ms("queries_breakdown.agent_breakdown.begin_time") as f64);
        b.num(_agent_db_t, "close", s.ms("queries_breakdown.agent_breakdown.close_time") as f64);
        b.num(_agent_db_t, "commit", s.ms("queries_breakdown.agent_breakdown.commit_time") as f64);
        b.num(_agent_db_t, "remove", s.ms("queries_breakdown.agent_breakdown.remove_time") as f64);
        b.num(_agent_db_t, "sql", s.ms("queries_breakdown.agent_breakdown.sql_time") as f64);
        b.num(_agent_db_t, "vacuum", s.ms("queries_breakdown.agent_breakdown.vacuum_time") as f64);
        b.num(_agent_db_t, "get_fragmentation", s.ms("queries_breakdown.agent_breakdown.get_fragmentation_time") as f64);
        b.num(_agent_db_t, "sleep", s.ms("queries_breakdown.agent_breakdown.sleep_time") as f64);
        let _agent_tables_t = b.obj();
        b.node(_agent_breakdown_t, "tables", _agent_tables_t);
        let _agent_tables_ciscat_t = b.obj();
        b.node(_agent_tables_t, "ciscat", _agent_tables_ciscat_t);
        b.num(_agent_tables_ciscat_t, "ciscat", s.ms("queries_breakdown.agent_breakdown.ciscat.ciscat_time") as f64);
        let _agent_tables_rootcheck_t = b.obj();
        b.node(_agent_tables_t, "rootcheck", _agent_tables_rootcheck_t);
        b.num(_agent_tables_rootcheck_t, "rootcheck", s.ms("queries_breakdown.agent_breakdown.rootcheck.rootcheck_time") as f64);
        let _agent_tables_sca_t = b.obj();
        b.node(_agent_tables_t, "sca", _agent_tables_sca_t);
        b.num(_agent_tables_sca_t, "sca", s.ms("queries_breakdown.agent_breakdown.sca.sca_time") as f64);
        let _agent_tables_sync_t = b.obj();
        b.node(_agent_tables_t, "sync", _agent_tables_sync_t);
        b.num(_agent_tables_sync_t, "dbsync", s.ms("queries_breakdown.agent_breakdown.sync.dbsync_time") as f64);
        let _agent_tables_syscheck_t = b.obj();
        b.node(_agent_tables_t, "syscheck", _agent_tables_syscheck_t);
        b.num(_agent_tables_syscheck_t, "fim_file", s.ms("queries_breakdown.agent_breakdown.syscheck.fim_file_time") as f64);
        b.num(_agent_tables_syscheck_t, "fim_registry", s.ms("queries_breakdown.agent_breakdown.syscheck.fim_registry_time") as f64);
        b.num(_agent_tables_syscheck_t, "fim_registry_key", s.ms("queries_breakdown.agent_breakdown.syscheck.fim_registry_key_time") as f64);
        b.num(_agent_tables_syscheck_t, "fim_registry_value", s.ms("queries_breakdown.agent_breakdown.syscheck.fim_registry_value_time") as f64);
        b.num(_agent_tables_syscheck_t, "syscheck", s.ms("queries_breakdown.agent_breakdown.syscheck.syscheck_time") as f64);
        let _agent_tables_syscollector_t = b.obj();
        b.node(_agent_tables_t, "syscollector", _agent_tables_syscollector_t);
        b.num(_agent_tables_syscollector_t, "syscollector_hotfixes", s.ms("queries_breakdown.agent_breakdown.syscollector.syscollector_hotfixes_time") as f64);
        b.num(_agent_tables_syscollector_t, "syscollector_hwinfo", s.ms("queries_breakdown.agent_breakdown.syscollector.syscollector_hwinfo_time") as f64);
        b.num(_agent_tables_syscollector_t, "syscollector_network_address", s.ms("queries_breakdown.agent_breakdown.syscollector.syscollector_network_address_time") as f64);
        b.num(_agent_tables_syscollector_t, "syscollector_network_iface", s.ms("queries_breakdown.agent_breakdown.syscollector.syscollector_network_iface_time") as f64);
        b.num(_agent_tables_syscollector_t, "syscollector_network_protocol", s.ms("queries_breakdown.agent_breakdown.syscollector.syscollector_network_protocol_time") as f64);
        b.num(_agent_tables_syscollector_t, "syscollector_osinfo", s.ms("queries_breakdown.agent_breakdown.syscollector.syscollector_osinfo_time") as f64);
        b.num(_agent_tables_syscollector_t, "syscollector_packages", s.ms("queries_breakdown.agent_breakdown.syscollector.syscollector_packages_time") as f64);
        b.num(_agent_tables_syscollector_t, "syscollector_ports", s.ms("queries_breakdown.agent_breakdown.syscollector.syscollector_ports_time") as f64);
        b.num(_agent_tables_syscollector_t, "syscollector_processes", s.ms("queries_breakdown.agent_breakdown.syscollector.syscollector_processes_time") as f64);
        b.num(_agent_tables_syscollector_t, "syscollector_groups", s.ms("queries_breakdown.agent_breakdown.syscollector.syscollector_groups_time") as f64);
        b.num(_agent_tables_syscollector_t, "syscollector_users", s.ms("queries_breakdown.agent_breakdown.syscollector.syscollector_users_time") as f64);
        b.num(_agent_tables_syscollector_t, "syscollector_browser_extensions", s.ms("queries_breakdown.agent_breakdown.syscollector.syscollector_browser_extensions_time") as f64);
        b.num(_agent_tables_syscollector_t, "syscollector_services", s.ms("queries_breakdown.agent_breakdown.syscollector.syscollector_services_time") as f64);
        let _agent_tables_syscollector_deprecated_t = b.obj();
        b.node(_agent_tables_syscollector_t, "deprecated", _agent_tables_syscollector_deprecated_t);
        b.num(_agent_tables_syscollector_deprecated_t, "hardware", s.ms("queries_breakdown.agent_breakdown.syscollector.deprecated.hardware_time") as f64);
        b.num(_agent_tables_syscollector_deprecated_t, "hotfix", s.ms("queries_breakdown.agent_breakdown.syscollector.deprecated.hotfix_time") as f64);
        b.num(_agent_tables_syscollector_deprecated_t, "netaddr", s.ms("queries_breakdown.agent_breakdown.syscollector.deprecated.netaddr_time") as f64);
        b.num(_agent_tables_syscollector_deprecated_t, "netinfo", s.ms("queries_breakdown.agent_breakdown.syscollector.deprecated.netinfo_time") as f64);
        b.num(_agent_tables_syscollector_deprecated_t, "netproto", s.ms("queries_breakdown.agent_breakdown.syscollector.deprecated.netproto_time") as f64);
        b.num(_agent_tables_syscollector_deprecated_t, "osinfo", s.ms("queries_breakdown.agent_breakdown.syscollector.deprecated.osinfo_time") as f64);
        b.num(_agent_tables_syscollector_deprecated_t, "package", s.ms("queries_breakdown.agent_breakdown.syscollector.deprecated.package_time") as f64);
        b.num(_agent_tables_syscollector_deprecated_t, "port", s.ms("queries_breakdown.agent_breakdown.syscollector.deprecated.port_time") as f64);
        b.num(_agent_tables_syscollector_deprecated_t, "process", s.ms("queries_breakdown.agent_breakdown.syscollector.deprecated.process_time") as f64);
        b.num(_execution_breakdown, "global", s.get_global_time() as f64);
        let _global_breakdown_t = b.obj();
        b.node(_execution_breakdown, "global_breakdown", _global_breakdown_t);
        let _global_db_t = b.obj();
        b.node(_global_breakdown_t, "db", _global_db_t);
        b.num(_global_db_t, "open", s.ms("queries_breakdown.global_breakdown.open_calls_time") as f64);
        b.num(_global_db_t, "backup", s.ms("queries_breakdown.global_breakdown.backup_time") as f64);
        b.num(_global_db_t, "sql", s.ms("queries_breakdown.global_breakdown.sql_time") as f64);
        b.num(_global_db_t, "vacuum", s.ms("queries_breakdown.global_breakdown.vacuum_time") as f64);
        b.num(_global_db_t, "get_fragmentation", s.ms("queries_breakdown.global_breakdown.get_fragmentation_time") as f64);
        b.num(_global_db_t, "sleep", s.ms("queries_breakdown.global_breakdown.sleep_time") as f64);
        let _global_tables_t = b.obj();
        b.node(_global_breakdown_t, "tables", _global_tables_t);
        let _global_tables_agent_t = b.obj();
        b.node(_global_tables_t, "agent", _global_tables_agent_t);
        b.num(_global_tables_agent_t, "delete-agent", s.ms("queries_breakdown.global_breakdown.agent.delete_agent_time") as f64);
        b.num(_global_tables_agent_t, "disconnect-agents", s.ms("queries_breakdown.global_breakdown.agent.disconnect_agents_time") as f64);
        b.num(_global_tables_agent_t, "find-agent", s.ms("queries_breakdown.global_breakdown.agent.find_agent_time") as f64);
        b.num(_global_tables_agent_t, "get-agent-info", s.ms("queries_breakdown.global_breakdown.agent.get_agent_info_time") as f64);
        b.num(_global_tables_agent_t, "get-agents-by-connection-status", s.ms("queries_breakdown.global_breakdown.agent.get_agents_by_connection_status_time") as f64);
        b.num(_global_tables_agent_t, "get-all-agents", s.ms("queries_breakdown.global_breakdown.agent.get_all_agents_time") as f64);
        b.num(_global_tables_agent_t, "get-distinct-groups", s.ms("queries_breakdown.global_breakdown.agent.get_distinct_groups_time") as f64);
        b.num(_global_tables_agent_t, "get-groups-integrity", s.ms("queries_breakdown.global_breakdown.agent.get_groups_integrity_time") as f64);
        b.num(_global_tables_agent_t, "recalculate-agent-group-hashes", s.ms("queries_breakdown.global_breakdown.agent.recalculate_agent_group_hashes_time") as f64);
        b.num(_global_tables_agent_t, "insert-agent", s.ms("queries_breakdown.global_breakdown.agent.insert_agent_time") as f64);
        b.num(_global_tables_agent_t, "reset-agents-connection", s.ms("queries_breakdown.global_breakdown.agent.reset_agents_connection_time") as f64);
        b.num(_global_tables_agent_t, "select-agent-group", s.ms("queries_breakdown.global_breakdown.agent.select_agent_group_time") as f64);
        b.num(_global_tables_agent_t, "select-agent-name", s.ms("queries_breakdown.global_breakdown.agent.select_agent_name_time") as f64);
        b.num(_global_tables_agent_t, "set-agent-groups", s.ms("queries_breakdown.global_breakdown.agent.set_agent_groups_time") as f64);
        b.num(_global_tables_agent_t, "sync-agent-groups-get", s.ms("queries_breakdown.global_breakdown.agent.sync_agent_groups_get_time") as f64);
        b.num(_global_tables_agent_t, "sync-agent-info-get", s.ms("queries_breakdown.global_breakdown.agent.sync_agent_info_get_time") as f64);
        b.num(_global_tables_agent_t, "sync-agent-info-set", s.ms("queries_breakdown.global_breakdown.agent.sync_agent_info_set_time") as f64);
        b.num(_global_tables_agent_t, "update-agent-data", s.ms("queries_breakdown.global_breakdown.agent.update_agent_data_time") as f64);
        b.num(_global_tables_agent_t, "update-agent-name", s.ms("queries_breakdown.global_breakdown.agent.update_agent_name_time") as f64);
        b.num(_global_tables_agent_t, "update-connection-status", s.ms("queries_breakdown.global_breakdown.agent.update_connection_status_time") as f64);
        b.num(_global_tables_agent_t, "update-status-code", s.ms("queries_breakdown.global_breakdown.agent.update_status_code_time") as f64);
        b.num(_global_tables_agent_t, "update-keepalive", s.ms("queries_breakdown.global_breakdown.agent.update_keepalive_time") as f64);
        let _global_tables_belongs_t = b.obj();
        b.node(_global_tables_t, "belongs", _global_tables_belongs_t);
        b.num(_global_tables_belongs_t, "get-group-agents", s.ms("queries_breakdown.global_breakdown.belongs.get_group_agent_time") as f64);
        b.num(_global_tables_belongs_t, "select-group-belong", s.ms("queries_breakdown.global_breakdown.belongs.select_group_belong_time") as f64);
        let _global_tables_group_t = b.obj();
        b.node(_global_tables_t, "group", _global_tables_group_t);
        b.num(_global_tables_group_t, "delete-group", s.ms("queries_breakdown.global_breakdown.group.delete_group_time") as f64);
        b.num(_global_tables_group_t, "find-group", s.ms("queries_breakdown.global_breakdown.group.find_group_time") as f64);
        b.num(_global_tables_group_t, "insert-agent-group", s.ms("queries_breakdown.global_breakdown.group.insert_agent_group_time") as f64);
        b.num(_global_tables_group_t, "select-groups", s.ms("queries_breakdown.global_breakdown.group.select_groups_time") as f64);
        let _global_tables_labels_t = b.obj();
        b.node(_global_tables_t, "labels", _global_tables_labels_t);
        b.num(_global_tables_labels_t, "get-labels", s.ms("queries_breakdown.global_breakdown.labels.get_labels_time") as f64);
        b.num(_execution_breakdown, "mitre", s.ms("queries_breakdown.mitre_breakdown.sql_time") as f64);
        let _mitre_breakdown_t = b.obj();
        b.node(_execution_breakdown, "mitre_breakdown", _mitre_breakdown_t);
        let _mitre_db_t = b.obj();
        b.node(_mitre_breakdown_t, "db", _mitre_db_t);
        b.num(_mitre_db_t, "sql", s.ms("queries_breakdown.mitre_breakdown.sql_time") as f64);
        b.num(_execution_breakdown, "task", s.get_task_time() as f64);
        let _task_breakdown_t = b.obj();
        b.node(_execution_breakdown, "task_breakdown", _task_breakdown_t);
        let _task_db_t = b.obj();
        b.node(_task_breakdown_t, "db", _task_db_t);
        b.num(_task_db_t, "sql", s.ms("queries_breakdown.task_breakdown.sql_time") as f64);
        let _task_tables_t = b.obj();
        b.node(_task_breakdown_t, "tables", _task_tables_t);
        let _task_tables_tasks_t = b.obj();
        b.node(_task_tables_t, "tasks", _task_tables_tasks_t);
        b.num(_task_tables_tasks_t, "delete_old", s.ms("queries_breakdown.task_breakdown.tasks.delete_old_time") as f64);
        b.num(_task_tables_tasks_t, "set_timeout", s.ms("queries_breakdown.task_breakdown.tasks.set_timeout_time") as f64);
        b.num(_task_tables_tasks_t, "upgrade", s.ms("queries_breakdown.task_breakdown.tasks.upgrade_time") as f64);
        b.num(_task_tables_tasks_t, "upgrade_cancel_tasks", s.ms("queries_breakdown.task_breakdown.tasks.upgrade_cancel_tasks_time") as f64);
        b.num(_task_tables_tasks_t, "upgrade_custom", s.ms("queries_breakdown.task_breakdown.tasks.upgrade_custom_time") as f64);
        b.num(_task_tables_tasks_t, "upgrade_get_status", s.ms("queries_breakdown.task_breakdown.tasks.upgrade_get_status_time") as f64);
        b.num(_task_tables_tasks_t, "upgrade_result", s.ms("queries_breakdown.task_breakdown.tasks.upgrade_result_time") as f64);
        b.num(_task_tables_tasks_t, "upgrade_update_status", s.ms("queries_breakdown.task_breakdown.tasks.upgrade_update_status_time") as f64);
        b.num(_execution_breakdown, "wazuhdb", s.ms("queries_breakdown.wazuhdb_breakdown.remove_time") as f64);
        let _wazuhdb_breakdown_t = b.obj();
        b.node(_execution_breakdown, "wazuhdb_breakdown", _wazuhdb_breakdown_t);
        let _wazuhdb_db_t = b.obj();
        b.node(_wazuhdb_breakdown_t, "db", _wazuhdb_db_t);
        b.num(_wazuhdb_db_t, "remove", s.ms("queries_breakdown.wazuhdb_breakdown.remove_time") as f64);
        b.build(wdb_state_json)
    }
}
