//! `enum wdb_stmt` and `SQL_STMT` (wazuh_db/wdb.h, wazuh_db/wdb.c).
//! Generated by tools/gen_stmts.py from the C sources: do not edit.

pub const WDB_STMT_FIM_LOAD: usize = 0;
pub const WDB_STMT_FIM_FIND_ENTRY: usize = 1;
pub const WDB_STMT_FIM_INSERT_ENTRY: usize = 2;
pub const WDB_STMT_FIM_INSERT_ENTRY2: usize = 3;
pub const WDB_STMT_FIM_UPDATE_ENTRY: usize = 4;
pub const WDB_STMT_FIM_DELETE: usize = 5;
pub const WDB_STMT_FIM_UPDATE_DATE: usize = 6;
pub const WDB_STMT_FIM_FIND_DATE_ENTRIES: usize = 7;
pub const WDB_STMT_FIM_GET_ATTRIBUTES: usize = 8;
pub const WDB_STMT_FIM_UPDATE_ATTRIBUTES: usize = 9;
pub const WDB_STMT_OSINFO_INSERT: usize = 10;
pub const WDB_STMT_OSINFO_INSERT2: usize = 11;
pub const WDB_STMT_OSINFO_DEL: usize = 12;
pub const WDB_STMT_OSINFO_GET: usize = 13;
pub const WDB_STMT_PROGRAM_INSERT: usize = 14;
pub const WDB_STMT_PROGRAM_INSERT2: usize = 15;
pub const WDB_STMT_PROGRAM_DEL: usize = 16;
pub const WDB_STMT_PROGRAM_UPD: usize = 17;
pub const WDB_STMT_PROGRAM_GET: usize = 18;
pub const WDB_STMT_PROGRAM_FIND: usize = 19;
pub const WDB_STMT_HWINFO_INSERT: usize = 20;
pub const WDB_STMT_HWINFO_INSERT2: usize = 21;
pub const WDB_STMT_HOTFIX_INSERT: usize = 22;
pub const WDB_STMT_HOTFIX_INSERT2: usize = 23;
pub const WDB_STMT_HWINFO_DEL: usize = 24;
pub const WDB_STMT_HOTFIX_DEL: usize = 25;
pub const WDB_STMT_PORT_INSERT: usize = 26;
pub const WDB_STMT_PORT_INSERT2: usize = 27;
pub const WDB_STMT_PORT_DEL: usize = 28;
pub const WDB_STMT_PROC_INSERT: usize = 29;
pub const WDB_STMT_PROC_INSERT2: usize = 30;
pub const WDB_STMT_PROC_DEL: usize = 31;
pub const WDB_STMT_NETINFO_INSERT: usize = 32;
pub const WDB_STMT_NETINFO_INSERT2: usize = 33;
pub const WDB_STMT_PROTO_INSERT: usize = 34;
pub const WDB_STMT_PROTO_INSERT2: usize = 35;
pub const WDB_STMT_ADDR_INSERT: usize = 36;
pub const WDB_STMT_ADDR_INSERT2: usize = 37;
pub const WDB_STMT_NETINFO_DEL: usize = 38;
pub const WDB_STMT_PROTO_DEL: usize = 39;
pub const WDB_STMT_ADDR_DEL: usize = 40;
pub const WDB_STMT_USER_INSERT: usize = 41;
pub const WDB_STMT_USER_INSERT2: usize = 42;
pub const WDB_STMT_GROUP_INSERT: usize = 43;
pub const WDB_STMT_GROUP_INSERT2: usize = 44;
pub const WDB_STMT_BROWSER_EXTENSION_INSERT: usize = 45;
pub const WDB_STMT_BROWSER_EXTENSION_INSERT2: usize = 46;
pub const WDB_STMT_SERVICE_INSERT: usize = 47;
pub const WDB_STMT_SERVICE_INSERT2: usize = 48;
pub const WDB_STMT_SERVICE_DEL: usize = 49;
pub const WDB_STMT_CISCAT_INSERT: usize = 50;
pub const WDB_STMT_CISCAT_DEL: usize = 51;
pub const WDB_STMT_SCAN_INFO_UPDATEFS: usize = 52;
pub const WDB_STMT_SCAN_INFO_UPDATEFE: usize = 53;
pub const WDB_STMT_SCAN_INFO_UPDATESS: usize = 54;
pub const WDB_STMT_SCAN_INFO_UPDATEES: usize = 55;
pub const WDB_STMT_SCAN_INFO_UPDATE1C: usize = 56;
pub const WDB_STMT_SCAN_INFO_UPDATE2C: usize = 57;
pub const WDB_STMT_SCAN_INFO_UPDATE3C: usize = 58;
pub const WDB_STMT_SCAN_INFO_GETFS: usize = 59;
pub const WDB_STMT_SCAN_INFO_GETFE: usize = 60;
pub const WDB_STMT_SCAN_INFO_GETSS: usize = 61;
pub const WDB_STMT_SCAN_INFO_GETES: usize = 62;
pub const WDB_STMT_SCAN_INFO_GET1C: usize = 63;
pub const WDB_STMT_SCAN_INFO_GET2C: usize = 64;
pub const WDB_STMT_SCAN_INFO_GET3C: usize = 65;
pub const WDB_STMT_SCA_FIND: usize = 66;
pub const WDB_STMT_SCA_UPDATE: usize = 67;
pub const WDB_STMT_SCA_INSERT: usize = 68;
pub const WDB_STMT_SCA_SCAN_INFO_INSERT: usize = 69;
pub const WDB_STMT_SCA_SCAN_INFO_UPDATE: usize = 70;
pub const WDB_STMT_SCA_INSERT_COMPLIANCE: usize = 71;
pub const WDB_STMT_SCA_INSERT_RULES: usize = 72;
pub const WDB_STMT_SCA_FIND_SCAN: usize = 73;
pub const WDB_STMT_SCA_SCAN_INFO_UPDATE_START: usize = 74;
pub const WDB_STMT_SCA_POLICY_FIND: usize = 75;
pub const WDB_STMT_SCA_POLICY_SHA256: usize = 76;
pub const WDB_STMT_SCA_POLICY_INSERT: usize = 77;
pub const WDB_STMT_SCA_CHECK_GET_ALL_RESULTS: usize = 78;
pub const WDB_STMT_SCA_POLICY_GET_ALL: usize = 79;
pub const WDB_STMT_SCA_POLICY_DELETE: usize = 80;
pub const WDB_STMT_SCA_CHECK_DELETE: usize = 81;
pub const WDB_STMT_SCA_SCAN_INFO_DELETE: usize = 82;
pub const WDB_STMT_SCA_CHECK_COMPLIANCE_DELETE: usize = 83;
pub const WDB_STMT_SCA_CHECK_RULES_DELETE: usize = 84;
pub const WDB_STMT_SCA_CHECK_DELETE_DISTINCT: usize = 85;
pub const WDB_STMT_FIM_SELECT_CHECKSUM: usize = 86;
pub const WDB_STMT_FIM_SELECT_CHECKSUM_RANGE: usize = 87;
pub const WDB_STMT_FIM_DELETE_AROUND: usize = 88;
pub const WDB_STMT_FIM_DELETE_RANGE: usize = 89;
pub const WDB_STMT_FIM_DELETE_BY_PK: usize = 90;
pub const WDB_STMT_FIM_CLEAR: usize = 91;
pub const WDB_STMT_SYNC_UPDATE_ATTEMPT_LEGACY: usize = 92;
pub const WDB_STMT_SYNC_UPDATE_ATTEMPT: usize = 93;
pub const WDB_STMT_SYNC_UPDATE_COMPLETION: usize = 94;
pub const WDB_STMT_SYNC_SET_COMPLETION: usize = 95;
pub const WDB_STMT_SYNC_GET_INFO: usize = 96;
pub const WDB_STMT_FIM_FILE_SELECT_CHECKSUM: usize = 97;
pub const WDB_STMT_FIM_FILE_SELECT_CHECKSUM_RANGE: usize = 98;
pub const WDB_STMT_FIM_FILE_CLEAR: usize = 99;
pub const WDB_STMT_FIM_FILE_DELETE_AROUND: usize = 100;
pub const WDB_STMT_FIM_FILE_DELETE_RANGE: usize = 101;
pub const WDB_STMT_FIM_FILE_DELETE_BY_PK: usize = 102;
pub const WDB_STMT_FIM_REGISTRY_SELECT_CHECKSUM: usize = 103;
pub const WDB_STMT_FIM_REGISTRY_SELECT_CHECKSUM_RANGE: usize = 104;
pub const WDB_STMT_FIM_REGISTRY_CLEAR: usize = 105;
pub const WDB_STMT_FIM_REGISTRY_DELETE_AROUND: usize = 106;
pub const WDB_STMT_FIM_REGISTRY_DELETE_RANGE: usize = 107;
pub const WDB_STMT_FIM_REGISTRY_KEY_SELECT_CHECKSUM: usize = 108;
pub const WDB_STMT_FIM_REGISTRY_KEY_SELECT_CHECKSUM_RANGE: usize = 109;
pub const WDB_STMT_FIM_REGISTRY_KEY_CLEAR: usize = 110;
pub const WDB_STMT_FIM_REGISTRY_KEY_DELETE_AROUND: usize = 111;
pub const WDB_STMT_FIM_REGISTRY_KEY_DELETE_RANGE: usize = 112;
pub const WDB_STMT_FIM_REGISTRY_VALUE_SELECT_CHECKSUM: usize = 113;
pub const WDB_STMT_FIM_REGISTRY_VALUE_SELECT_CHECKSUM_RANGE: usize = 114;
pub const WDB_STMT_FIM_REGISTRY_VALUE_CLEAR: usize = 115;
pub const WDB_STMT_FIM_REGISTRY_VALUE_DELETE_AROUND: usize = 116;
pub const WDB_STMT_FIM_REGISTRY_VALUE_DELETE_RANGE: usize = 117;
pub const WDB_STMT_FIM_REGISTRY_DELETE_BY_PK: usize = 118;
pub const WDB_STMT_ROOTCHECK_INSERT_PM: usize = 119;
pub const WDB_STMT_ROOTCHECK_UPDATE_PM: usize = 120;
pub const WDB_STMT_ROOTCHECK_DELETE_PM: usize = 121;
pub const WDB_STMT_GLOBAL_INSERT_AGENT: usize = 122;
pub const WDB_STMT_GLOBAL_UPDATE_AGENT_NAME: usize = 123;
pub const WDB_STMT_GLOBAL_UPDATE_AGENT_VERSION: usize = 124;
pub const WDB_STMT_GLOBAL_UPDATE_AGENT_VERSION_IP: usize = 125;
pub const WDB_STMT_GLOBAL_LABELS_GET: usize = 126;
pub const WDB_STMT_GLOBAL_LABELS_DEL: usize = 127;
pub const WDB_STMT_GLOBAL_LABELS_SET: usize = 128;
pub const WDB_STMT_GLOBAL_UPDATE_AGENT_KEEPALIVE: usize = 129;
pub const WDB_STMT_GLOBAL_UPDATE_AGENT_CONNECTION_STATUS: usize = 130;
pub const WDB_STMT_GLOBAL_UPDATE_AGENT_STATUS_CODE: usize = 131;
pub const WDB_STMT_GLOBAL_DELETE_AGENT: usize = 132;
pub const WDB_STMT_GLOBAL_SELECT_AGENT_NAME: usize = 133;
pub const WDB_STMT_GLOBAL_FIND_AGENT: usize = 134;
pub const WDB_STMT_GLOBAL_FIND_GROUP: usize = 135;
pub const WDB_STMT_GLOBAL_UPDATE_AGENT_GROUPS_HASH: usize = 136;
pub const WDB_STMT_GLOBAL_INSERT_AGENT_GROUP: usize = 137;
pub const WDB_STMT_GLOBAL_SELECT_GROUP_BELONG: usize = 138;
pub const WDB_STMT_GLOBAL_INSERT_AGENT_BELONG: usize = 139;
pub const WDB_STMT_GLOBAL_DELETE_AGENT_BELONG: usize = 140;
pub const WDB_STMT_GLOBAL_DELETE_TUPLE_BELONG: usize = 141;
pub const WDB_STMT_GLOBAL_DELETE_GROUP: usize = 142;
pub const WDB_STMT_GLOBAL_GROUP_BELONG_FIND: usize = 143;
pub const WDB_STMT_GLOBAL_GROUP_BELONG_GET: usize = 144;
pub const WDB_STMT_GLOBAL_SELECT_GROUPS: usize = 145;
pub const WDB_STMT_GLOBAL_SYNC_REQ_FULL_GET: usize = 146;
pub const WDB_STMT_GLOBAL_SYNC_REQ_STATUS_GET: usize = 147;
pub const WDB_STMT_GLOBAL_SYNC_REQ_KEEPALIVE_GET: usize = 148;
pub const WDB_STMT_GLOBAL_SYNC_GET: usize = 149;
pub const WDB_STMT_GLOBAL_SYNC_SET: usize = 150;
pub const WDB_STMT_GLOBAL_GROUP_SYNC_REQ_GET: usize = 151;
pub const WDB_STMT_GLOBAL_GROUP_SYNC_ALL_GET: usize = 152;
pub const WDB_STMT_GLOBAL_GROUP_SYNCREQ_FIND: usize = 153;
pub const WDB_STMT_GLOBAL_AGENT_GROUPS_NUMBER_GET: usize = 154;
pub const WDB_STMT_GLOBAL_GROUP_SYNC_SET: usize = 155;
pub const WDB_STMT_GLOBAL_GROUP_PRIORITY_GET: usize = 156;
pub const WDB_STMT_GLOBAL_GROUP_CSV_GET: usize = 157;
pub const WDB_STMT_GLOBAL_GROUP_CTX_SET: usize = 158;
pub const WDB_STMT_GLOBAL_GROUP_HASH_GET: usize = 159;
pub const WDB_STMT_GLOBAL_GROUP_HASH_SET: usize = 160;
pub const WDB_STMT_GLOBAL_UPDATE_AGENT_INFO: usize = 161;
pub const WDB_STMT_GLOBAL_GET_GROUPS: usize = 162;
pub const WDB_STMT_GLOBAL_GET_AGENTS: usize = 163;
pub const WDB_STMT_GLOBAL_GET_AGENTS_AND_GROUP: usize = 164;
pub const WDB_STMT_GLOBAL_GET_AGENTS_CONTEXT: usize = 165;
pub const WDB_STMT_GLOBAL_GET_AGENTS_BY_CONNECTION_STATUS: usize = 166;
pub const WDB_STMT_GLOBAL_GET_AGENTS_BY_CONNECTION_STATUS_AND_NODE: usize = 167;
pub const WDB_STMT_GLOBAL_GET_AGENT_INFO: usize = 168;
pub const WDB_STMT_GLOBAL_GET_AGENTS_TO_DISCONNECT: usize = 169;
pub const WDB_STMT_GLOBAL_RESET_CONNECTION_STATUS: usize = 170;
pub const WDB_STMT_GLOBAL_AGENT_EXISTS: usize = 171;
pub const WDB_STMT_TASK_INSERT_TASK: usize = 172;
pub const WDB_STMT_TASK_GET_LAST_AGENT_TASK: usize = 173;
pub const WDB_STMT_TASK_GET_LAST_AGENT_UPGRADE_TASK: usize = 174;
pub const WDB_STMT_TASK_UPDATE_TASK_STATUS: usize = 175;
pub const WDB_STMT_TASK_GET_TASK_BY_STATUS: usize = 176;
pub const WDB_STMT_TASK_DELETE_OLD_TASKS: usize = 177;
pub const WDB_STMT_TASK_DELETE_TASK: usize = 178;
pub const WDB_STMT_TASK_CANCEL_PENDING_UPGRADE_TASKS: usize = 179;
pub const WDB_STMT_PRAGMA_JOURNAL_WAL: usize = 180;
pub const WDB_STMT_PRAGMA_ENABLE_FOREIGN_KEYS: usize = 181;
pub const WDB_STMT_PRAGMA_SYNCHRONOUS_NORMAL: usize = 182;
pub const WDB_STMT_SYSCOLLECTOR_PROCESSES_SELECT_CHECKSUM: usize = 183;
pub const WDB_STMT_SYSCOLLECTOR_PROCESSES_SELECT_CHECKSUM_RANGE: usize = 184;
pub const WDB_STMT_SYSCOLLECTOR_PROCESSES_DELETE_AROUND: usize = 185;
pub const WDB_STMT_SYSCOLLECTOR_PROCESSES_DELETE_RANGE: usize = 186;
pub const WDB_STMT_SYSCOLLECTOR_PROCESSES_CLEAR: usize = 187;
pub const WDB_STMT_SYSCOLLECTOR_PROCESSES_DELETE_BY_PK: usize = 188;
pub const WDB_STMT_SYSCOLLECTOR_PACKAGES_SELECT_CHECKSUM: usize = 189;
pub const WDB_STMT_SYSCOLLECTOR_PACKAGES_SELECT_CHECKSUM_RANGE: usize = 190;
pub const WDB_STMT_SYSCOLLECTOR_PACKAGES_DELETE_AROUND: usize = 191;
pub const WDB_STMT_SYSCOLLECTOR_PACKAGES_DELETE_RANGE: usize = 192;
pub const WDB_STMT_SYSCOLLECTOR_PACKAGES_CLEAR: usize = 193;
pub const WDB_STMT_SYSCOLLECTOR_PACKAGES_DELETE_BY_PK: usize = 194;
pub const WDB_STMT_SYSCOLLECTOR_HOTFIXES_SELECT_CHECKSUM: usize = 195;
pub const WDB_STMT_SYSCOLLECTOR_HOTFIXES_SELECT_CHECKSUM_RANGE: usize = 196;
pub const WDB_STMT_SYSCOLLECTOR_HOTFIXES_DELETE_AROUND: usize = 197;
pub const WDB_STMT_SYSCOLLECTOR_HOTFIXES_DELETE_RANGE: usize = 198;
pub const WDB_STMT_SYSCOLLECTOR_HOTFIXES_CLEAR: usize = 199;
pub const WDB_STMT_SYSCOLLECTOR_HOTFIXES_DELETE_BY_PK: usize = 200;
pub const WDB_STMT_SYSCOLLECTOR_PORTS_SELECT_CHECKSUM: usize = 201;
pub const WDB_STMT_SYSCOLLECTOR_PORTS_SELECT_CHECKSUM_RANGE: usize = 202;
pub const WDB_STMT_SYSCOLLECTOR_PORTS_DELETE_AROUND: usize = 203;
pub const WDB_STMT_SYSCOLLECTOR_PORTS_DELETE_RANGE: usize = 204;
pub const WDB_STMT_SYSCOLLECTOR_PORTS_DELETE_BY_PK: usize = 205;
pub const WDB_STMT_SYSCOLLECTOR_PORTS_CLEAR: usize = 206;
pub const WDB_STMT_SYSCOLLECTOR_NETPROTO_SELECT_CHECKSUM: usize = 207;
pub const WDB_STMT_SYSCOLLECTOR_NETPROTO_SELECT_CHECKSUM_RANGE: usize = 208;
pub const WDB_STMT_SYSCOLLECTOR_NETPROTO_DELETE_AROUND: usize = 209;
pub const WDB_STMT_SYSCOLLECTOR_NETPROTO_DELETE_RANGE: usize = 210;
pub const WDB_STMT_SYSCOLLECTOR_NETPROTO_DELETE_BY_PK: usize = 211;
pub const WDB_STMT_SYSCOLLECTOR_NETPROTO_CLEAR: usize = 212;
pub const WDB_STMT_SYSCOLLECTOR_NETADDRESS_SELECT_CHECKSUM: usize = 213;
pub const WDB_STMT_SYSCOLLECTOR_NETADDRESS_SELECT_CHECKSUM_RANGE: usize = 214;
pub const WDB_STMT_SYSCOLLECTOR_NETADDRESS_DELETE_AROUND: usize = 215;
pub const WDB_STMT_SYSCOLLECTOR_NETADDRESS_DELETE_RANGE: usize = 216;
pub const WDB_STMT_SYSCOLLECTOR_NETADDRESS_DELETE_BY_PK: usize = 217;
pub const WDB_STMT_SYSCOLLECTOR_NETADDRESS_CLEAR: usize = 218;
pub const WDB_STMT_SYSCOLLECTOR_NETINFO_SELECT_CHECKSUM: usize = 219;
pub const WDB_STMT_SYSCOLLECTOR_NETINFO_SELECT_CHECKSUM_RANGE: usize = 220;
pub const WDB_STMT_SYSCOLLECTOR_NETINFO_DELETE_AROUND: usize = 221;
pub const WDB_STMT_SYSCOLLECTOR_NETINFO_DELETE_RANGE: usize = 222;
pub const WDB_STMT_SYSCOLLECTOR_NETINFO_DELETE_BY_PK: usize = 223;
pub const WDB_STMT_SYSCOLLECTOR_NETINFO_CLEAR: usize = 224;
pub const WDB_STMT_SYSCOLLECTOR_HWINFO_SELECT_CHECKSUM: usize = 225;
pub const WDB_STMT_SYSCOLLECTOR_HWINFO_SELECT_CHECKSUM_RANGE: usize = 226;
pub const WDB_STMT_SYSCOLLECTOR_HWINFO_DELETE_AROUND: usize = 227;
pub const WDB_STMT_SYSCOLLECTOR_HWINFO_DELETE_RANGE: usize = 228;
pub const WDB_STMT_SYSCOLLECTOR_HWINFO_DELETE_BY_PK: usize = 229;
pub const WDB_STMT_SYSCOLLECTOR_HWINFO_CLEAR: usize = 230;
pub const WDB_STMT_SYSCOLLECTOR_OSINFO_SELECT_CHECKSUM: usize = 231;
pub const WDB_STMT_SYSCOLLECTOR_OSINFO_SELECT_CHECKSUM_RANGE: usize = 232;
pub const WDB_STMT_SYSCOLLECTOR_OSINFO_DELETE_AROUND: usize = 233;
pub const WDB_STMT_SYSCOLLECTOR_OSINFO_DELETE_RANGE: usize = 234;
pub const WDB_STMT_SYSCOLLECTOR_OSINFO_DELETE_BY_PK: usize = 235;
pub const WDB_STMT_SYSCOLLECTOR_OSINFO_CLEAR: usize = 236;
pub const WDB_STMT_SYSCOLLECTOR_USERS_SELECT_CHECKSUM: usize = 237;
pub const WDB_STMT_SYSCOLLECTOR_USERS_SELECT_CHECKSUM_RANGE: usize = 238;
pub const WDB_STMT_SYSCOLLECTOR_USERS_DELETE_AROUND: usize = 239;
pub const WDB_STMT_SYSCOLLECTOR_USERS_DELETE_RANGE: usize = 240;
pub const WDB_STMT_SYSCOLLECTOR_USERS_DELETE_BY_PK: usize = 241;
pub const WDB_STMT_SYSCOLLECTOR_USERS_CLEAR: usize = 242;
pub const WDB_STMT_SYSCOLLECTOR_GROUPS_SELECT_CHECKSUM: usize = 243;
pub const WDB_STMT_SYSCOLLECTOR_GROUPS_SELECT_CHECKSUM_RANGE: usize = 244;
pub const WDB_STMT_SYSCOLLECTOR_GROUPS_DELETE_AROUND: usize = 245;
pub const WDB_STMT_SYSCOLLECTOR_GROUPS_DELETE_RANGE: usize = 246;
pub const WDB_STMT_SYSCOLLECTOR_GROUPS_DELETE_BY_PK: usize = 247;
pub const WDB_STMT_SYSCOLLECTOR_GROUPS_CLEAR: usize = 248;
pub const WDB_STMT_SYSCOLLECTOR_BROWSER_EXTENSIONS_SELECT_CHECKSUM: usize = 249;
pub const WDB_STMT_SYSCOLLECTOR_BROWSER_EXTENSIONS_SELECT_CHECKSUM_RANGE: usize = 250;
pub const WDB_STMT_SYSCOLLECTOR_BROWSER_EXTENSIONS_DELETE_AROUND: usize = 251;
pub const WDB_STMT_SYSCOLLECTOR_BROWSER_EXTENSIONS_DELETE_RANGE: usize = 252;
pub const WDB_STMT_SYSCOLLECTOR_BROWSER_EXTENSIONS_DELETE_BY_PK: usize = 253;
pub const WDB_STMT_SYSCOLLECTOR_BROWSER_EXTENSIONS_CLEAR: usize = 254;
pub const WDB_STMT_SYSCOLLECTOR_SERVICES_SELECT_CHECKSUM: usize = 255;
pub const WDB_STMT_SYSCOLLECTOR_SERVICES_SELECT_CHECKSUM_RANGE: usize = 256;
pub const WDB_STMT_SYSCOLLECTOR_SERVICES_DELETE_AROUND: usize = 257;
pub const WDB_STMT_SYSCOLLECTOR_SERVICES_DELETE_RANGE: usize = 258;
pub const WDB_STMT_SYSCOLLECTOR_SERVICES_DELETE_BY_PK: usize = 259;
pub const WDB_STMT_SYSCOLLECTOR_SERVICES_CLEAR: usize = 260;
pub const WDB_STMT_SYS_HOTFIXES_GET: usize = 261;
pub const WDB_STMT_SYS_PROGRAMS_GET: usize = 262;
/// `WDB_STMT_SIZE`
pub const WDB_STMT_SIZE: usize = 263;

/// `SQL_STMT`
pub static SQL_STMT: [&str; WDB_STMT_SIZE] = [
    "SELECT changes, size, perm, uid, gid, md5, sha1, uname, gname, mtime, inode, sha256, date, attributes, symbolic_path FROM fim_entry WHERE file = ?;",
    "SELECT 1 FROM fim_entry WHERE file = ?",
    "INSERT INTO fim_entry (file, type, size, perm, uid, gid, md5, sha1, uname, gname, mtime, inode, sha256, attributes, symbolic_path, full_path) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT OR REPLACE INTO fim_entry (file, type, date, size, perm, uid, gid, md5, sha1, uname, gname, mtime, inode, sha256, attributes, symbolic_path, checksum, arch, value_name, value_type, full_path) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "UPDATE fim_entry SET date = strftime('%s', 'now'), changes = ?, size = ?, perm = ?, uid = ?, gid = ?, md5 = ?, sha1 = ?, uname = ?, gname = ?, mtime = ?, inode = ?, sha256 = ?, attributes = ?, symbolic_path = ? WHERE file = ?;",
    "DELETE FROM fim_entry WHERE full_path = ?;",
    "UPDATE fim_entry SET date = strftime('%s', 'now') WHERE file = ?;",
    "SELECT full_path, changes, size, perm, uid, gid, md5, sha1, uname, gname, mtime, inode, sha256, date, attributes, symbolic_path FROM fim_entry WHERE date < ?;",
    "SELECT file, attributes from fim_entry WHERE attributes IS NOT '0';",
    "UPDATE fim_entry SET attributes = ? WHERE file = ?;",
    "INSERT INTO sys_osinfo (scan_id, scan_time, hostname, architecture, os_name, os_version, os_codename, os_major, os_minor,  os_patch, os_build, os_platform, sysname, release, version, os_release, os_display_version, checksum, reference) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT OR REPLACE INTO sys_osinfo (scan_id, scan_time, hostname, architecture, os_name, os_version, os_codename, os_major, os_minor,  os_patch, os_build, os_platform, sysname, release, version, os_release, os_display_version, checksum, reference) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "DELETE FROM sys_osinfo;",
    "SELECT * FROM sys_osinfo;",
    "INSERT INTO sys_programs (scan_id, scan_time, format, name, priority, section, size, vendor, install_time, version, architecture, multiarch, source, description, location, checksum, item_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT OR REPLACE INTO sys_programs (scan_id, scan_time, format, name, priority, section, size, vendor, install_time, version, architecture, multiarch, source, description, location, checksum, item_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "DELETE FROM sys_programs WHERE scan_id != ?;",
    "UPDATE SYS_PROGRAMS SET CPE = ?, MSU_NAME = ? WHERE SCAN_ID = ? AND FORMAT IS ? AND NAME IS ? AND VENDOR IS ? AND VERSION IS ? AND ARCHITECTURE IS ?;",
    "SELECT CPE, MSU_NAME, FORMAT, NAME, VENDOR, VERSION, ARCHITECTURE FROM SYS_PROGRAMS WHERE SCAN_ID != ?;",
    "SELECT 1 FROM sys_programs WHERE item_id = ?;",
    "INSERT INTO sys_hwinfo (scan_id, scan_time, board_serial, cpu_name, cpu_cores, cpu_mhz, ram_total, ram_free, ram_usage, checksum) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT OR REPLACE INTO sys_hwinfo (scan_id, scan_time, board_serial, cpu_name, cpu_cores, cpu_mhz, ram_total, ram_free, ram_usage, checksum) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT INTO sys_hotfixes (scan_id, scan_time, hotfix, checksum) VALUES (?, ?, ?, ?);",
    "INSERT OR REPLACE INTO sys_hotfixes (scan_id, scan_time, hotfix, checksum) VALUES (?, ?, ?, ?);",
    "DELETE FROM sys_hwinfo;",
    "DELETE FROM sys_hotfixes WHERE scan_id != ?;",
    "INSERT INTO sys_ports (scan_id, scan_time, protocol, local_ip, local_port, remote_ip, remote_port, tx_queue, rx_queue, inode, state, PID, process, checksum, item_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT OR REPLACE INTO sys_ports (scan_id, scan_time, protocol, local_ip, local_port, remote_ip, remote_port, tx_queue, rx_queue, inode, state, PID, process, checksum, item_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "DELETE FROM sys_ports WHERE scan_id != ?;",
    "INSERT INTO sys_processes (scan_id, scan_time, pid, name, state, ppid, utime, stime, cmd, argvs, euser, ruser, suser, egroup, rgroup, sgroup, fgroup, priority, nice, size, vm_size, resident, share, start_time, pgrp, session, nlwp, tgid, tty, processor, checksum) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
    "INSERT OR REPLACE INTO sys_processes (scan_id, scan_time, pid, name, state, ppid, utime, stime, cmd, argvs, euser, ruser, suser, egroup, rgroup, sgroup, fgroup, priority, nice, size, vm_size, resident, share, start_time, pgrp, session, nlwp, tgid, tty, processor, checksum) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
    "DELETE FROM sys_processes WHERE scan_id != ?;",
    "INSERT INTO sys_netiface (scan_id, scan_time, name, adapter, type, state, mtu, mac, tx_packets, rx_packets, tx_bytes, rx_bytes, tx_errors, rx_errors, tx_dropped, rx_dropped, checksum, item_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT OR REPLACE INTO sys_netiface (scan_id, scan_time, name, adapter, type, state, mtu, mac, tx_packets, rx_packets, tx_bytes, rx_bytes, tx_errors, rx_errors, tx_dropped, rx_dropped, checksum, item_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT INTO sys_netproto (scan_id, iface, type, gateway, dhcp, metric, checksum, item_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT OR REPLACE INTO sys_netproto (scan_id, iface, type, gateway, dhcp, metric, checksum, item_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT INTO sys_netaddr (scan_id, iface, proto, address, netmask, broadcast, checksum, item_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT OR REPLACE INTO sys_netaddr (scan_id, iface, proto, address, netmask, broadcast, checksum, item_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?);",
    "DELETE FROM sys_netiface WHERE scan_id != ?;",
    "DELETE FROM sys_netproto WHERE scan_id != ?;",
    "DELETE FROM sys_netaddr WHERE scan_id != ?;",
    "INSERT INTO sys_users (scan_id, scan_time, user_name, user_full_name, user_home, user_id, user_uid_signed, user_uuid, user_groups, user_group_id, user_group_id_signed, user_created, user_roles, user_shell, user_type, user_is_hidden, user_is_remote, user_last_login, user_auth_failed_count, user_auth_failed_timestamp, user_password_last_change, user_password_expiration_date, user_password_hash_algorithm, user_password_inactive_days, user_password_max_days_between_changes, user_password_min_days_between_changes, user_password_status, user_password_warning_days_before_expiration, process_pid, host_ip, login_status, login_type, login_tty, checksum) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT OR REPLACE INTO sys_users (scan_id, scan_time, user_name, user_full_name, user_home, user_id, user_uid_signed, user_uuid, user_groups, user_group_id, user_group_id_signed, user_created, user_roles, user_shell, user_type, user_is_hidden, user_is_remote, user_last_login, user_auth_failed_count, user_auth_failed_timestamp, user_password_last_change, user_password_expiration_date, user_password_hash_algorithm, user_password_inactive_days, user_password_max_days_between_changes, user_password_min_days_between_changes, user_password_status, user_password_warning_days_before_expiration, process_pid, host_ip, login_status, login_type, login_tty, checksum) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT INTO sys_groups (scan_id, scan_time, group_id, group_name, group_description, group_id_signed, group_uuid, group_is_hidden, group_users, checksum) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT OR REPLACE INTO sys_groups (scan_id, scan_time, group_id, group_name, group_description, group_id_signed, group_uuid, group_is_hidden, group_users, checksum) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT INTO sys_browser_extensions (scan_id, scan_time, browser_name, user_id, package_name, package_id, package_version, package_description, package_vendor, package_build_version, package_path, browser_profile_name, browser_profile_path, package_reference, package_permissions, package_type, package_enabled, package_visible, package_autoupdate, package_persistent, package_from_webstore, browser_profile_referenced, package_installed, file_hash_sha256, checksum, item_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT OR REPLACE INTO sys_browser_extensions (scan_id, scan_time, browser_name, user_id, package_name, package_id, package_version, package_description, package_vendor, package_build_version, package_path, browser_profile_name, browser_profile_path, package_reference, package_permissions, package_type, package_enabled, package_visible, package_autoupdate, package_persistent, package_from_webstore, browser_profile_referenced, package_installed, file_hash_sha256, checksum, item_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT INTO sys_services (scan_id, scan_time, service_id, service_name, service_description, service_type, service_state, service_sub_state, service_enabled, service_start_type, service_restart, service_frequency, service_starts_on_mount, service_starts_on_path_modified, service_starts_on_not_empty_directory, service_inetd_compatibility, process_pid, process_executable, process_args, process_user_name, process_group_name, process_working_directory, process_root_directory, file_path, service_address, log_file_path, error_log_file_path, service_exit_code, service_win32_exit_code, service_following, service_object_path, service_target_ephemeral_id, service_target_type, service_target_address, checksum, item_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "INSERT OR REPLACE INTO sys_services (scan_id, scan_time, service_id, service_name, service_description, service_type, service_state, service_sub_state, service_enabled, service_start_type, service_restart, service_frequency, service_starts_on_mount, service_starts_on_path_modified, service_starts_on_not_empty_directory, service_inetd_compatibility, process_pid, process_executable, process_args, process_user_name, process_group_name, process_working_directory, process_root_directory, file_path, service_address, log_file_path, error_log_file_path, service_exit_code, service_win32_exit_code, service_following, service_object_path, service_target_ephemeral_id, service_target_type, service_target_address, checksum, item_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "DELETE FROM sys_services WHERE scan_id != ?;",
    "INSERT INTO ciscat_results (scan_id, scan_time, benchmark, profile, pass, fail, error, notchecked, unknown, score) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",
    "DELETE FROM ciscat_results WHERE scan_id != ?;",
    "UPDATE scan_info SET first_start = ?, start_scan = ? WHERE module = ?;",
    "UPDATE scan_info SET first_end = ?, end_scan = ? WHERE module = ?;",
    "UPDATE scan_info SET start_scan = ? WHERE module = ?;",
    "UPDATE scan_info SET end_scan = ? WHERE module = ?;",
    "UPDATE scan_info SET fim_first_check = ? WHERE module = ?;",
    "UPDATE scan_info SET fim_second_check = ? WHERE module = ?;",
    "UPDATE scan_info SET fim_third_check = ? WHERE module = ?;",
    "SELECT first_start FROM scan_info WHERE module = ?;",
    "SELECT first_end FROM scan_info WHERE module = ?;",
    "SELECT start_scan FROM scan_info WHERE module = ?;",
    "SELECT end_scan FROM scan_info WHERE module = ?;",
    "SELECT fim_first_check FROM scan_info WHERE module = ?;",
    "SELECT fim_second_check FROM scan_info WHERE module = ?;",
    "SELECT fim_third_check FROM scan_info WHERE module = ?;",
    "SELECT id,result FROM sca_check WHERE id = ?;",
    "UPDATE sca_check SET scan_id = ?, result = ?, reason = ? WHERE id = ?;",
    "INSERT INTO sca_check (id,scan_id,title,description,rationale,remediation,file,directory,process,registry,`references`,result,policy_id,command,reason,condition) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);",
    "INSERT INTO sca_scan_info (start_scan,end_scan,id,policy_id,pass,fail,invalid,total_checks,score,hash) VALUES (?,?,?,?,?,?,?,?,?,?);",
    "UPDATE sca_scan_info SET start_scan = ?, end_scan = ?, id = ?, pass = ?, fail = ?, invalid = ?, total_checks = ?, score = ?, hash = ? WHERE policy_id = ?;",
    "INSERT INTO sca_check_compliance (id_check,`key`,`value`) VALUES(?,?,?);",
    "INSERT INTO sca_check_rules (id_check,`type`, rule) VALUES(?,?,?);",
    "SELECT policy_id,hash,id FROM sca_scan_info WHERE policy_id = ?;",
    "UPDATE sca_scan_info SET start_scan = ?, end_scan = ?, id = ?, pass = ?, fail = ?, invalid = ?, total_checks = ?, score = ?, hash = ? WHERE policy_id = ?;",
    "SELECT id FROM sca_policy WHERE id = ?;",
    "SELECT hash_file FROM sca_policy WHERE id = ?;",
    "INSERT INTO sca_policy (name,file,id,description,`references`,hash_file) VALUES(?,?,?,?,?,?);",
    "SELECT result FROM sca_check WHERE policy_id = ? ORDER BY id;",
    "SELECT id FROM sca_policy;",
    "DELETE FROM sca_policy WHERE id = ?;",
    "DELETE FROM sca_check WHERE policy_id = ?;",
    "DELETE FROM sca_scan_info WHERE policy_id = ?;",
    "DELETE FROM sca_check_compliance WHERE id_check NOT IN ( SELECT id FROM sca_check);",
    "DELETE FROM sca_check_rules WHERE id_check NOT IN ( SELECT id FROM sca_check);",
    "DELETE FROM sca_check WHERE scan_id != ? AND policy_id = ?;",
    "SELECT checksum FROM fim_entry ORDER BY file;",
    "SELECT checksum FROM fim_entry WHERE file BETWEEN ? and ? ORDER BY file;",
    "DELETE FROM fim_entry WHERE file < ? OR file > ? RETURNING file;",
    "DELETE FROM fim_entry WHERE file > ? AND file < ? RETURNING file;",
    "DELETE FROM fim_entry WHERE file = ? RETURNING file;",
    "DELETE FROM fim_entry;",
    "UPDATE sync_info SET last_attempt = ? WHERE component = ?;",
    "UPDATE sync_info SET last_attempt = ?, last_agent_checksum = ?, last_manager_checksum = ?, n_attempts = n_attempts + 1 WHERE component = ?;",
    "UPDATE sync_info SET last_attempt = ?, last_completion = ?, last_agent_checksum = ?, last_manager_checksum = ?, n_attempts = n_attempts + 1, n_completions = n_completions + 1 WHERE component = ?;",
    "UPDATE sync_info SET last_completion = ? WHERE component = ?;",
    "SELECT * FROM sync_info WHERE component = ?;",
    "SELECT checksum FROM fim_entry WHERE type='file' ORDER BY file;",
    "SELECT checksum FROM fim_entry WHERE type='file' AND file BETWEEN ? and ? ORDER BY file;",
    "DELETE FROM fim_entry WHERE type='file';",
    "DELETE FROM fim_entry WHERE type='file' AND (file < ? OR file > ?) RETURNING file;",
    "DELETE FROM fim_entry WHERE type='file' AND (file > ? AND file < ?) RETURNING file;",
    "DELETE FROM fim_entry WHERE type='file' AND file = ? RETURNING file;",
    "SELECT checksum FROM fim_entry WHERE (type='registry_key' OR type='registry_value') ORDER BY full_path",
    "SELECT checksum FROM fim_entry WHERE (type='registry_key' OR type='registry_value') AND full_path BETWEEN ? AND ? ORDER BY full_path",
    "DELETE FROM fim_entry WHERE type='registry_key' OR type='registry_value';",
    "DELETE FROM fim_entry WHERE (type='registry_key' OR type='registry_value') AND (full_path < ? OR full_path > ?) RETURNING full_path;",
    "DELETE FROM fim_entry WHERE (type='registry_key' OR type='registry_value') AND (full_path > ? AND full_path < ?) RETURNING full_path;",
    "SELECT checksum FROM fim_entry WHERE type='registry_key' ORDER BY full_path",
    "SELECT checksum FROM fim_entry WHERE type='registry_key' AND full_path BETWEEN ? AND ? ORDER BY full_path",
    "DELETE FROM fim_entry WHERE type='registry_key';",
    "DELETE FROM fim_entry WHERE type='registry_key' AND (full_path < ? OR full_path > ?) RETURNING full_path;",
    "DELETE FROM fim_entry WHERE type='registry_key' AND (full_path > ? AND full_path < ?) RETURNING full_path;",
    "SELECT checksum FROM fim_entry WHERE type='registry_value' ORDER BY full_path",
    "SELECT checksum FROM fim_entry WHERE type='registry_value' AND full_path BETWEEN ? AND ? ORDER BY full_path",
    "DELETE FROM fim_entry WHERE type='registry_value';",
    "DELETE FROM fim_entry WHERE type='registry_value' AND (full_path < ? OR full_path > ?) RETURNING full_path;",
    "DELETE FROM fim_entry WHERE type='registry_value' AND (full_path > ? AND full_path < ?) RETURNING full_path;",
    "DELETE FROM fim_entry WHERE (type='registry_key' OR type='registry_value') AND full_path = ? RETURNING full_path;",
    "INSERT INTO pm_event (date_first, date_last, log, pci_dss, cis) VALUES (?, ?, ?, ?, ?);",
    "UPDATE pm_event SET date_last = ? WHERE log = ?;",
    "DELETE FROM pm_event;",
    "INSERT INTO agent (id, name, ip, register_ip, internal_key, date_add, `group`) VALUES (?,?,?,?,?,?,?);",
    "UPDATE agent SET name = ? WHERE id = ?;",
    "UPDATE agent SET os_name = ?, os_version = ?, os_major = ?, os_minor = ?, os_codename = ?, os_platform = ?, os_build = ?, os_uname = ?, os_arch = ?, version = ?, config_sum = ?, merged_sum = ?, manager_host = ?, node_name = ?, last_keepalive = (CASE WHEN id = 0 THEN 253402300799 ELSE STRFTIME('%s', 'NOW') END), connection_status = ?, sync_status = ?, group_config_status = ? WHERE id = ?;",
    "UPDATE agent SET os_name = ?, os_version = ?, os_major = ?, os_minor = ?, os_codename = ?, os_platform = ?, os_build = ?, os_uname = ?, os_arch = ?, version = ?, config_sum = ?, merged_sum = ?, manager_host = ?, node_name = ?, last_keepalive = (CASE WHEN id = 0 THEN 253402300799 ELSE STRFTIME('%s', 'NOW') END), ip = ?, connection_status = ?, sync_status = ?, group_config_status = ? WHERE id = ?;",
    "SELECT * FROM labels WHERE id = ?;",
    "DELETE FROM labels WHERE id = ?;",
    "INSERT INTO labels (id, key, value) VALUES (?,?,?);",
    "UPDATE agent SET last_keepalive = STRFTIME('%s', 'NOW'), connection_status = ?, sync_status = ?, disconnection_time = 0, status_code = 0 WHERE id = ?;",
    "UPDATE agent SET connection_status = ?, sync_status = ?, disconnection_time = ?, status_code = ? WHERE id = ?;",
    "UPDATE agent SET status_code = ?, version = ?, sync_status = ? WHERE id = ?;",
    "DELETE FROM agent WHERE id = ?;",
    "SELECT name FROM agent WHERE id = ?;",
    "SELECT id FROM agent WHERE name = ? AND (register_ip = ? OR register_ip LIKE ? || '/_%');",
    "SELECT id FROM `group` WHERE name = ?;",
    "UPDATE agent SET group_hash = ? WHERE id = ?;",
    "INSERT INTO `group` (name) VALUES(?);",
    "SELECT name FROM belongs JOIN `group` ON id = id_group WHERE id_agent = ? order by priority;",
    "INSERT OR REPLACE INTO belongs (id_group, id_agent, priority) VALUES(?,?,?);",
    "DELETE FROM belongs WHERE id_agent = ?;",
    "DELETE FROM belongs WHERE id_group = ? and id_agent = ?;",
    "DELETE FROM `group` WHERE name = ?;",
    "SELECT id_agent FROM belongs WHERE id_group = (SELECT id FROM 'group' WHERE name = ?);",
    "SELECT id_agent FROM belongs WHERE id_group = (SELECT id FROM 'group' WHERE name = ?) AND id_agent > ?;",
    "SELECT name FROM `group`;",
    "SELECT id, name, ip, os_name, os_version, os_major, os_minor, os_codename, os_build, os_platform, os_uname, os_arch, version, config_sum, merged_sum, manager_host, node_name, last_keepalive, connection_status, disconnection_time, group_config_status, status_code FROM agent WHERE id > ? AND sync_status = 'syncreq' LIMIT 1;",
    "SELECT id, last_keepalive, connection_status, disconnection_time, status_code FROM agent WHERE id > ? AND sync_status = 'syncreq_status' LIMIT 1;",
    "SELECT id, last_keepalive FROM agent WHERE id > ? AND sync_status = 'syncreq_keepalive' LIMIT 1;",
    "SELECT sync_status FROM agent WHERE id = ?;",
    "UPDATE agent SET sync_status = ? WHERE id = ?;",
    "SELECT id, name FROM agent WHERE id > ? AND group_sync_status = 'syncreq' AND date_add < ? LIMIT 1;",
    "SELECT id, name FROM agent WHERE id > ? AND date_add < ? LIMIT 1;",
    "SELECT 1 FROM agent WHERE group_sync_status = 'syncreq';",
    "SELECT count(id_group) groups_number from belongs WHERE id_agent = ?;",
    "UPDATE agent SET group_sync_status = ? WHERE id = ?;",
    "SELECT MAX(priority) FROM belongs WHERE id_agent=?;",
    "SELECT `group` from agent where id = ?;",
    "UPDATE agent SET 'group' = ?, group_hash = ?, group_sync_status = ? WHERE id = ?;",
    "SELECT group_hash FROM agent WHERE id > 0 AND group_hash IS NOT NULL ORDER BY id;",
    "UPDATE agent SET 'group' = ?, group_hash = ? WHERE id = ?;",
    "UPDATE agent SET config_sum = :config_sum, ip = :ip, manager_host = :manager_host, merged_sum = :merged_sum, name = :name, node_name = :node_name, os_arch = :os_arch, os_build = :os_build, os_codename = :os_codename, os_major = :os_major, os_minor = :os_minor, os_name = :os_name, os_platform = :os_platform, os_uname = :os_uname, os_version = :os_version, version = :version, last_keepalive = :last_keepalive, connection_status = :connection_status, disconnection_time = :disconnection_time, group_config_status = :group_config_status, status_code= :status_code, sync_status = :sync_status WHERE id = :id;",
    "SELECT DISTINCT `group`, group_hash from agent WHERE id > 0 AND group_hash > ? ORDER BY group_hash;",
    "SELECT id FROM agent WHERE id > ?;",
    "SELECT id, `group` FROM agent WHERE id > ?;",
    "SELECT id,version,name,ip FROM agent;",
    "SELECT id FROM agent WHERE id > ? AND connection_status = ?;",
    "SELECT id FROM agent WHERE id > ? AND connection_status = ? AND node_name = ? ORDER BY id LIMIT ?;",
    "SELECT * FROM agent WHERE id = ?;",
    "SELECT id FROM agent WHERE id > ? AND (connection_status = 'active' OR connection_status = 'pending') AND last_keepalive < ?;",
    "UPDATE agent SET connection_status = 'disconnected', status_code = ?, sync_status = ?, disconnection_time = STRFTIME('%s', 'NOW') where connection_status != 'disconnected' AND connection_status != 'never_connected' AND id != 0;",
    "SELECT EXISTS(SELECT 1 FROM agent WHERE id=?);",
    "INSERT INTO TASKS VALUES(NULL,?,?,?,?,?,?,?,?);",
    "SELECT *, MAX(CREATE_TIME) FROM TASKS WHERE AGENT_ID = ?;",
    "SELECT *, MAX(CREATE_TIME) FROM TASKS WHERE AGENT_ID = ? AND (COMMAND = 'upgrade' OR COMMAND = 'upgrade_custom');",
    "UPDATE TASKS SET STATUS = ?, LAST_UPDATE_TIME = ?, ERROR_MESSAGE = ? WHERE TASK_ID = ?;",
    "SELECT * FROM TASKS WHERE STATUS = ?;",
    "DELETE FROM TASKS WHERE CREATE_TIME <= ?;",
    "DELETE FROM TASKS WHERE TASK_ID = ?;",
    "UPDATE TASKS SET STATUS = 'Cancelled', LAST_UPDATE_TIME = ? WHERE NODE = ? AND STATUS = 'Pending' AND (COMMAND = 'upgrade' OR COMMAND = 'upgrade_custom');",
    "PRAGMA journal_mode=WAL;",
    "PRAGMA foreign_keys=ON;",
    "PRAGMA synchronous=1;",
    "SELECT checksum FROM sys_processes WHERE checksum != 'legacy' AND checksum != '' ORDER BY pid;",
    "SELECT checksum FROM sys_processes WHERE pid BETWEEN ? and ? AND checksum != 'legacy' AND checksum != '' ORDER BY pid;",
    "DELETE FROM sys_processes WHERE pid < ? OR pid > ? OR checksum = 'legacy' OR checksum = '' RETURNING pid;",
    "DELETE FROM sys_processes WHERE pid > ? AND pid < ? RETURNING pid;",
    "DELETE FROM sys_processes;",
    "DELETE FROM sys_processes WHERE pid = ? RETURNING pid;",
    "SELECT checksum FROM sys_programs WHERE checksum != 'legacy' AND checksum != '' ORDER BY item_id;",
    "SELECT checksum FROM sys_programs WHERE item_id BETWEEN ? and ? AND checksum != 'legacy' AND checksum != '' ORDER BY item_id;",
    "DELETE FROM sys_programs WHERE item_id < ? OR item_id > ? OR checksum = 'legacy' OR checksum = '' RETURNING name, version, architecture, format, location, item_id;",
    "DELETE FROM sys_programs WHERE item_id > ? AND item_id < ? RETURNING name, version, architecture, format, location, item_id;",
    "DELETE FROM sys_programs;",
    "DELETE FROM sys_programs WHERE item_id = ? RETURNING name, version, architecture, format, location, item_id;",
    "SELECT checksum FROM sys_hotfixes WHERE checksum != 'legacy' AND checksum != '' ORDER BY hotfix;",
    "SELECT checksum FROM sys_hotfixes WHERE hotfix BETWEEN ? and ? AND checksum != 'legacy' AND checksum != '' ORDER BY hotfix;",
    "DELETE FROM sys_hotfixes WHERE hotfix < ? OR hotfix > ? OR checksum = 'legacy' OR checksum = '' RETURNING hotfix;",
    "DELETE FROM sys_hotfixes WHERE hotfix > ? AND hotfix < ? RETURNING hotfix;",
    "DELETE FROM sys_hotfixes;",
    "DELETE FROM sys_hotfixes WHERE hotfix = ? RETURNING hotfix;",
    "SELECT checksum FROM sys_ports WHERE checksum != 'legacy' AND checksum != '' ORDER BY item_id;",
    "SELECT checksum FROM sys_ports WHERE item_id BETWEEN ? and ? AND checksum != 'legacy' AND checksum != '' ORDER BY item_id;",
    "DELETE FROM sys_ports WHERE item_id < ? OR item_id > ? OR checksum = 'legacy' OR checksum = '' RETURNING protocol, local_ip, local_port, inode, item_id;",
    "DELETE FROM sys_ports WHERE item_id > ? AND item_id < ? RETURNING protocol, local_ip, local_port, inode, item_id;",
    "DELETE FROM sys_ports WHERE item_id = ? RETURNING protocol, local_ip, local_port, inode, item_id;",
    "DELETE FROM sys_ports;",
    "SELECT checksum FROM sys_netproto WHERE checksum != 'legacy' AND checksum != '' ORDER BY item_id;",
    "SELECT checksum FROM sys_netproto WHERE item_id BETWEEN ? and ? AND checksum != 'legacy' AND checksum != '' ORDER BY item_id;",
    "DELETE FROM sys_netproto WHERE item_id < ? OR item_id > ? OR checksum = 'legacy' OR checksum = '' RETURNING item_id;",
    "DELETE FROM sys_netproto WHERE item_id > ? AND item_id < ? RETURNING item_id;",
    "DELETE FROM sys_netproto WHERE item_id = ? RETURNING item_id;",
    "DELETE FROM sys_netproto;",
    "SELECT checksum FROM sys_netaddr WHERE checksum != 'legacy' AND checksum != '' ORDER BY item_id;",
    "SELECT checksum FROM sys_netaddr WHERE item_id BETWEEN ? and ? AND checksum != 'legacy' AND checksum != '' ORDER BY item_id;",
    "DELETE FROM sys_netaddr WHERE item_id < ? OR item_id > ? OR checksum = 'legacy' OR checksum = '' RETURNING item_id;",
    "DELETE FROM sys_netaddr WHERE item_id > ? AND item_id < ? RETURNING item_id;",
    "DELETE FROM sys_netaddr WHERE item_id = ? RETURNING item_id;",
    "DELETE FROM sys_netaddr;",
    "SELECT checksum FROM sys_netiface WHERE checksum != 'legacy' AND checksum != '' ORDER BY item_id;",
    "SELECT checksum FROM sys_netiface WHERE item_id BETWEEN ? and ? AND checksum != 'legacy' AND checksum != '' ORDER BY item_id;",
    "DELETE FROM sys_netiface WHERE item_id < ? OR item_id > ? OR checksum = 'legacy' OR checksum = '' RETURNING item_id;",
    "DELETE FROM sys_netiface WHERE item_id > ? AND item_id < ? RETURNING item_id;",
    "DELETE FROM sys_netiface WHERE item_id = ? RETURNING item_id;",
    "DELETE FROM sys_netiface;",
    "SELECT checksum FROM sys_hwinfo WHERE checksum != 'legacy' AND checksum != '' ORDER BY board_serial;",
    "SELECT checksum FROM sys_hwinfo WHERE board_serial BETWEEN ? and ? AND checksum != 'legacy' AND checksum != '' ORDER BY board_serial;",
    "DELETE FROM sys_hwinfo WHERE board_serial < ? OR board_serial > ? OR checksum = 'legacy' OR checksum = '' RETURNING board_serial;",
    "DELETE FROM sys_hwinfo WHERE board_serial > ? AND board_serial < ? RETURNING board_serial;",
    "DELETE FROM sys_hwinfo WHERE board_serial = ? RETURNING board_serial;",
    "DELETE FROM sys_hwinfo;",
    "SELECT checksum FROM sys_osinfo WHERE checksum != 'legacy' AND checksum != '' ORDER BY os_name;",
    "SELECT checksum FROM sys_osinfo WHERE os_name BETWEEN ? and ? AND checksum != 'legacy' AND checksum != '' ORDER BY os_name;",
    "DELETE FROM sys_osinfo WHERE os_name < ? OR os_name > ? OR checksum = 'legacy' OR checksum = '' RETURNING os_name;",
    "DELETE FROM sys_osinfo WHERE os_name > ? AND os_name < ? RETURNING os_name;",
    "DELETE FROM sys_osinfo WHERE os_name = ? RETURNING os_name;",
    "DELETE FROM sys_osinfo;",
    "SELECT checksum FROM sys_users WHERE checksum != 'legacy' AND checksum != '' ORDER BY user_name;",
    "SELECT checksum FROM sys_users WHERE user_name BETWEEN ? and ? AND checksum != 'legacy' AND checksum != '' ORDER BY user_name;",
    "DELETE FROM sys_users WHERE user_name < ? OR user_name > ? OR checksum = 'legacy' OR checksum = '' RETURNING user_name;",
    "DELETE FROM sys_users WHERE user_name > ? AND user_name < ? RETURNING user_name;",
    "DELETE FROM sys_users WHERE user_name = ? RETURNING user_name;",
    "DELETE FROM sys_users;",
    "SELECT checksum FROM sys_groups WHERE checksum != 'legacy' AND checksum != '' ORDER BY group_name;",
    "SELECT checksum FROM sys_groups WHERE group_name BETWEEN ? and ? AND checksum != 'legacy' AND checksum != '' ORDER BY group_name;",
    "DELETE FROM sys_groups WHERE group_name < ? OR group_name > ? OR checksum = 'legacy' OR checksum = '' RETURNING group_name;",
    "DELETE FROM sys_groups WHERE group_name > ? AND group_name < ? RETURNING group_name;",
    "DELETE FROM sys_groups WHERE group_name = ? RETURNING group_name;",
    "DELETE FROM sys_groups;",
    "SELECT checksum FROM sys_browser_extensions WHERE checksum != 'legacy' AND checksum != '' ORDER BY item_id;",
    "SELECT checksum FROM sys_browser_extensions WHERE item_id BETWEEN ? and ? AND checksum != 'legacy' AND checksum != '' ORDER BY item_id;",
    "DELETE FROM sys_browser_extensions WHERE item_id < ? OR item_id > ? OR checksum = 'legacy' OR checksum = '' RETURNING item_id;",
    "DELETE FROM sys_browser_extensions WHERE item_id > ? AND item_id < ? RETURNING item_id;",
    "DELETE FROM sys_browser_extensions WHERE item_id = ? RETURNING item_id;",
    "DELETE FROM sys_browser_extensions;",
    "SELECT checksum FROM sys_services WHERE checksum != 'legacy' AND checksum != '' ORDER BY item_id;",
    "SELECT checksum FROM sys_services WHERE item_id BETWEEN ? and ? AND checksum != 'legacy' AND checksum != '' ORDER BY item_id;",
    "DELETE FROM sys_services WHERE item_id < ? OR item_id > ? OR checksum = 'legacy' OR checksum = '' RETURNING item_id;",
    "DELETE FROM sys_services WHERE item_id > ? AND item_id < ? RETURNING item_id;",
    "DELETE FROM sys_services WHERE item_id = ? RETURNING item_id;",
    "DELETE FROM sys_services;",
    "SELECT HOTFIX FROM SYS_HOTFIXES;",
    "SELECT DISTINCT NAME, VERSION, ARCHITECTURE, VENDOR, FORMAT, SOURCE, CPE, MSU_NAME, ITEM_ID, DESCRIPTION, LOCATION, SIZE, INSTALL_TIME FROM SYS_PROGRAMS;",
];
