[workspace]
resolver = "2"
members = [
    "crates/siem-core",
    "crates/siem-engine",
    "crates/siem-agent",
    "crates/siem-agent-linux",
    "crates/siem-api",
    "crates/provigil-common",
    "crates/auth-service",
    "crates/siem-vuln-detector",
    "crates/siem-remoted",
    "crates/siem-sqlite",
    "crates/siem-wdb",
    "crates/siem-cdb",
    "crates/siem-rootcheck",
    "crates/siem-task-manager",
    "crates/siem-syscollector",
    "crates/siem-harvester",
    "crates/siem-agent-upgrade",
    "crates/siem-util",
    "crates/siem-syscheckd",
    "crates/siem-shared-modules",
    "crates/siem-shared",
    "crates/siem-maild",
    "crates/siem-integratord",
    "crates/siem-csyslogd",
    "crates/siem-execd",
    "crates/siem-crypto",
    "crates/siem-authd",
    "crates/siem-monitord",
    "crates/siem-agentlessd",
    "crates/siem-reportd",
    "crates/siem-logcollector",
    "crates/siem-parser-gen",
    "crates/siem-regex",
    "crates/siem-xml",
    "crates/siem-config",
    "crates/siem-ipc",
    "crates/siem-fileop",
    "crates/siem-cjson",
    "crates/siem-analysisd",
    "crates/siem-log",
    "crates/siem-daemon",
    "crates/siem-njson",
    "crates/siem-router",
]

