[package]
name = "siem-harvester"
version = "0.1.0"
edition = "2021"
description = "Wazuh Common Schema (WCS) Inventory & FIM Harvester Pipeline (wm_inventory_harvester)"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
siem-core = { path = "../siem-core" }
siem-syscollector = { path = "../siem-syscollector" }
siem-wdb = { path = "../siem-wdb" }
